// =============================================================================
// VELO Frontend -- MasterStudentsView Screen Tests (T8, ПРОМТ №431)
// =============================================================================
//
// Generated by probekit-screen-test. Same mount idiom as
// MyBookingsView.test.ts, but this screen is the OTHER of VELO's two screen
// patterns and the test shape follows from that:
//
//   PATTERN B (local-ref): state is `const students/loading/error = ref(...)`
//   in the component, fed by a direct getStudents() call in onMounted
//   (MasterStudentsView.vue:125-141). There is no store, so NO pinia is needed
//   at all -- the seam is @/api/masters, the module the screen itself imports.
//   Mocking a store here would mock a layer this screen does not have.
//
// Honest scope note on the error rung: MasterStudentsView.vue:135-137 does
// `catch { error.value = 'Попробуйте ещё раз' }` -- the backend's own message is
// SWALLOWED. So the error test below proves the screen's fallback constant
// reaches the DOM; it deliberately does NOT claim the backend message surfaces
// (it cannot). MyBookingsView is the contrast: it binds :description="store.error"
// and the real message does get through, which that file's test asserts.
//
// No time pinning needed -- this screen reads no clock.
// =============================================================================

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { createApp, nextTick, type App } from 'vue'
import MasterStudentsView from '@/views/master/MasterStudentsView.vue'
import * as mastersApi from '@/api/masters'
import type { StudentListItem } from '@/api/types'

vi.mock('@/api/masters')

const push = vi.fn()
vi.mock('vue-router', () => ({
  useRouter: () => ({ push }),
}))

function student(id: string, overrides: Partial<StudentListItem> = {}): StudentListItem {
  return {
    id,
    name: `Ученик ${id}`,
    avatar_url: null,
    practices_count: 3,
    needs_attention: false,
    ...overrides,
  }
}

function page(items: StudentListItem[]) {
  return { items, total: items.length, limit: 20, offset: 0 }
}

let app: App | null = null
let host: HTMLElement | null = null

function mount(): HTMLElement {
  host = document.createElement('div')
  document.body.appendChild(host)
  app = createApp(MasterStudentsView)
  app.mount(host)
  return host
}

// onMounted(load) awaits getStudents() -- mount tick, promise continuation,
// re-render.
async function flush(): Promise<void> {
  await nextTick()
  await nextTick()
  await nextTick()
}

function text(): string {
  return host?.textContent ?? ''
}

function rows(): HTMLElement[] {
  return Array.from(host?.querySelectorAll<HTMLElement>('.students__row') ?? [])
}

beforeEach(() => {
  vi.mocked(mastersApi.getStudents).mockReset().mockResolvedValue(page([]))
  push.mockReset()
})

afterEach(() => {
  app?.unmount()
  host?.remove()
  app = null
  host = null
  vi.clearAllMocks()
})

describe('MasterStudentsView', () => {
  describe('state ladder', () => {
    it('shows the loader while the fetch is in flight', async () => {
      vi.mocked(mastersApi.getStudents).mockReturnValue(
        new Promise(() => {}) as Promise<ReturnType<typeof page>>,
      )
      mount()
      await flush()

      expect(host?.querySelector('.students__state')).not.toBeNull()
      expect(text()).not.toContain('Учеников пока нет')
    })

    it('on failure: shows the error state with the screen fallback copy', async () => {
      vi.mocked(mastersApi.getStudents).mockRejectedValue(new Error('boom'))
      mount()
      await flush()

      expect(text()).toContain('Не удалось загрузить учеников')
      // The screen's own constant -- NOT the rejection's message, which its
      // bare `catch {}` discards. Asserting 'boom' here would be a lie.
      expect(text()).toContain('Попробуйте ещё раз')
      expect(text()).not.toContain('boom')
    })

    it('error retry: «Повторить» re-runs the fetch and recovers into content', async () => {
      vi.mocked(mastersApi.getStudents).mockRejectedValueOnce(new Error('boom'))
      mount()
      await flush()
      expect(text()).toContain('Не удалось загрузить учеников')

      vi.mocked(mastersApi.getStudents).mockResolvedValue(
        page([student('s1', { name: 'Анна' })]),
      )
      const retry = Array.from(host?.querySelectorAll('button') ?? []).find((b) =>
        b.textContent?.includes('Повторить'),
      )
      expect(retry).toBeDefined()
      retry?.click()
      await flush()

      expect(text()).toContain('Анна')
      expect(text()).not.toContain('Не удалось загрузить учеников')
    })

    it('empty: no students at all', async () => {
      mount()
      await flush()

      expect(text()).toContain('Учеников пока нет')
    })

    it('content: renders each student with its practice count', async () => {
      vi.mocked(mastersApi.getStudents).mockResolvedValue(
        page([student('s1', { name: 'Анна', practices_count: 7 })]),
      )
      mount()
      await flush()

      expect(text()).toContain('Анна')
      expect(text()).toContain('Практик: 7')
      expect(rows()).toHaveLength(1)
    })

    it('needs_attention drives the inline warning badge, and only for that student', async () => {
      vi.mocked(mastersApi.getStudents).mockResolvedValue(
        page([
          student('s1', { name: 'Анна', needs_attention: true }),
          student('s2', { name: 'Борис', needs_attention: false }),
        ]),
      )
      mount()
      await flush()

      const attn = host?.querySelectorAll('.students__attn') ?? []
      expect(attn).toHaveLength(1)
      expect(text()).toContain('Требует внимания')
    })
  })

  describe('preview cap (MasterStudentsView.vue:150-157)', () => {
    it('shows only the first 10 and hides the rest behind the show-more pill', async () => {
      vi.mocked(mastersApi.getStudents).mockResolvedValue(
        page(Array.from({ length: 14 }, (_, i) => student(`s${i}`, { name: `Ученик${i}` }))),
      )
      mount()
      await flush()

      expect(rows()).toHaveLength(10)
      expect(text()).toContain('4')
      expect(text()).toContain('Ученик0')
      expect(text()).not.toContain('Ученик13')
    })

    it('tapping show-more reveals the full list', async () => {
      vi.mocked(mastersApi.getStudents).mockResolvedValue(
        page(Array.from({ length: 14 }, (_, i) => student(`s${i}`, { name: `Ученик${i}` }))),
      )
      mount()
      await flush()

      const pill = Array.from(host?.querySelectorAll('button') ?? []).find((b) =>
        b.textContent?.includes('ещё'),
      )
      expect(pill).toBeDefined()
      pill?.click()
      await flush()

      expect(rows()).toHaveLength(14)
      expect(text()).toContain('Ученик13')
    })

    it('12 students with no cap applied would be wrong -- exactly 10 render before expanding', async () => {
      vi.mocked(mastersApi.getStudents).mockResolvedValue(
        page(Array.from({ length: 12 }, (_, i) => student(`s${i}`))),
      )
      mount()
      await flush()

      expect(rows()).toHaveLength(10)
    })
  })

  describe('search', () => {
    it('filters the loaded page client-side, case-insensitively', async () => {
      vi.mocked(mastersApi.getStudents).mockResolvedValue(
        page([student('s1', { name: 'Анна' }), student('s2', { name: 'Борис' })]),
      )
      mount()
      await flush()

      const input = host?.querySelector<HTMLInputElement>('input')
      expect(input).not.toBeNull()
      input!.value = 'анн'
      input!.dispatchEvent(new Event('input'))
      await flush()

      expect(text()).toContain('Анна')
      expect(text()).not.toContain('Борис')
      // Filtering must not re-hit the network -- it is client-side by design.
      expect(mastersApi.getStudents).toHaveBeenCalledTimes(1)
    })

    it('a query matching nobody shows the no-match empty, NOT the no-students-at-all empty', async () => {
      // Two distinct empties (MasterStudentsView.vue:86-97) -- collapsing them
      // would tell a master with students that they have none.
      vi.mocked(mastersApi.getStudents).mockResolvedValue(page([student('s1', { name: 'Анна' })]))
      mount()
      await flush()

      const input = host?.querySelector<HTMLInputElement>('input')
      input!.value = 'zzz'
      input!.dispatchEvent(new Event('input'))
      await flush()

      expect(text()).toContain('Никого не найдено')
      expect(text()).not.toContain('Учеников пока нет')
    })
  })

  describe('navigation', () => {
    it('tapping a row opens the student profile, carrying the name forward in the query', async () => {
      // MasterStudentsView.vue:159-166: the detail endpoint carries no name, so
      // the list must pass it through or the next screen renders nameless.
      vi.mocked(mastersApi.getStudents).mockResolvedValue(
        page([student('s1', { name: 'Анна' })]),
      )
      mount()
      await flush()

      rows()[0]?.click()
      await flush()

      expect(push).toHaveBeenCalledWith({
        name: 'master-student-profile',
        params: { id: 's1' },
        query: { name: 'Анна' },
      })
    })

    it('the message button does NOT navigate (@click.stop)', async () => {
      vi.mocked(mastersApi.getStudents).mockResolvedValue(
        page([student('s1', { name: 'Анна' })]),
      )
      mount()
      await flush()

      host?.querySelector<HTMLElement>('.students__msg')?.click()
      await flush()

      expect(push).not.toHaveBeenCalled()
    })
  })
})
