// =============================================================================
// VELO Frontend -- MasterStudentProfileView Screen Tests
// =============================================================================
//
// Generated by probekit-screen-test. Sibling of MasterStudentsView.test.ts (the
// list this screen is pushed from); same pattern, same seam.
//
//   PATTERN B (local-ref): detail/loading/error are `ref()`s owned by the
//   component, fed by ONE direct getStudent() call in onMounted
//   (MasterStudentProfileView.vue:128-143). No store anywhere in the screen's
//   subtree (grepped: VHeader/VAvatar/VStatCard/VLoader/VEmptyState/VShowMore/
//   MoodAvatar/SendMessageModal resolve no Pinia store), so NO pinia is
//   installed here -- the Pattern-A corollary about unstubbed children needing
//   a real Pinia does not bite this screen. The seam is @/api/masters.
//
// TICKS = 3, counted, not copied. The chain onMounted kicks off is exactly:
//   (1) mount + onMounted(load) -> load() suspends at `await getStudent(id)`
//   (2) the mocked promise's continuation -> detail/loading assigned
//   (3) the re-render flush
// Identical chain to MasterStudentsView (3). Nothing here awaits a store action
// awaiting an API wrapper, so the deeper counts (5/6/10) do not apply.
//
// NO time pinning: the screen reads no wall clock. formatShortDate() takes the
// fixture's own ISO string and formats it in a FIXED timezone (UTC default,
// format.ts:118-129) -- so "9 июня" is a literal derivation of the fixture, not
// of today. Date fixtures below are literals and stay correct forever.
//
// NO money: nothing here renders formatMoney, so the ru-NBSP trap is absent.
// Asserted strings contain only ordinary spaces (verified by codepoint).
//
// REAL BUG found while writing this file, FIXED in №441: formatShortDate()
// zero-padded days 1..9 ("09 июня") despite documenting "9 июня" — an en-CA
// format-matcher resolution, not this screen's fault, affecting 13 surfaces
// app-wide. The tripwire in the feedbackRows block below now asserts the
// CORRECT output and is the screen-level proof the util fix reaches the DOM.
//
// TRAP -- the ?name= query is NOT what its comment claims. .vue:117-124 says the
// list forwards ?name= "for an instant pre-fetch render". It cannot: the hero is
// behind `v-else` of `v-if="loading"` (.vue:20,34-39) and `loading` starts true,
// so NOTHING renders the name until the fetch resolves -- by which point
// detail.name has already won the `||`. The query fallback is reachable only when
// the backend returns an EMPTY name. Tests below assert the real behaviour and
// pin the loading gate; they do not repeat the comment's claim. See the report.
//
// TRAP -- route.params.id is read INSIDE load() (.vue:136), never in a watcher.
// The screen fetches on mount and on «Повторить» only; a params change would not
// refetch. Same shape the neighbour found on MasterPracticeDetailView. Not
// asserted as a feature -- the route is a static mock here; noted so the next
// reader does not assume reactivity that is not there.
//
// TRAP -- SendMessageModal teleports .v-modal__overlay to document.body
// (VModal.vue:20-22). Queried on document.body (SC-07) and reaped in afterEach
// (SC-13); "closed" is asserted as `.v-modal-leave-active` present, never as the
// overlay being gone (SC-13b) -- happy-dom never fires the transitionend.
//
// No v-show on this screen (grepped: 0) -- host-wide textContent is safe here,
// but per-section queries are still scoped because BOTH sections render the same
// «посмотреть еще» label and «Хорошо» is BOTH the high mood label and the good
// rating label.
// =============================================================================

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { createApp, nextTick, type App } from 'vue'
import MasterStudentProfileView from '@/views/master/MasterStudentProfileView.vue'
import * as mastersApi from '@/api/masters'
import type {
  StudentDetailResponse,
  StudentCheckinItem,
  StudentFeedbackItem,
} from '@/api/types'

vi.mock('@/api/masters')

const push = vi.fn()
const back = vi.fn()

// Mutable behind the composable so a test can pick the id/query it needs.
// Plain object, not reactive: the screen reads params imperatively inside load()
// and query inside a computed that re-runs off `detail` (a real ref).
const routeState: {
  params: Record<string, string>
  query: Record<string, string | string[] | undefined>
} = { params: { id: 's1' }, query: {} }

vi.mock('vue-router', () => ({
  useRoute: () => routeState,
  useRouter: () => ({ push, back }),
}))

const info = vi.fn()
vi.mock('@/composables/useToast', () => ({
  useToast: () => ({ info, success: vi.fn(), error: vi.fn(), dismiss: vi.fn() }),
}))

// -- fixtures ---------------------------------------------------------------

function checkin(over: Partial<StudentCheckinItem> = {}): StudentCheckinItem {
  return { mood: 5, comment: null, created_at: '2026-06-09T10:00:00Z', ...over }
}

function feedback(over: Partial<StudentFeedbackItem> = {}): StudentFeedbackItem {
  return { rating: 5, comment: null, created_at: '2026-06-09T10:00:00Z', ...over }
}

function detail(over: Partial<StudentDetailResponse> = {}): StudentDetailResponse {
  return {
    name: 'Анна Кузнецова',
    avatar_url: null,
    practices_count: 0,
    hours: 0,
    satisfaction_pct: null,
    recent_checkins: [],
    feedbacks: [],
    ...over,
  }
}

// -- mount ------------------------------------------------------------------

let app: App | null = null
let host: HTMLElement | null = null

function mount(): HTMLElement {
  host = document.createElement('div')
  document.body.appendChild(host)
  app = createApp(MasterStudentProfileView)
  app.mount(host)
  return host
}

async function flush(): Promise<void> {
  for (let i = 0; i < 3; i++) await nextTick()
}

function text(): string {
  return host?.textContent ?? ''
}

function ciRows(): HTMLElement[] {
  return Array.from(host?.querySelectorAll<HTMLElement>('.profile__ci') ?? [])
}

function fbRows(): HTMLElement[] {
  return Array.from(host?.querySelectorAll<HTMLElement>('.profile__fb') ?? [])
}

function showMorePills(): HTMLElement[] {
  return Array.from(host?.querySelectorAll<HTMLElement>('.v-show-more') ?? [])
}

/** The LIVE overlay -- excludes a corpse parked mid-test by an earlier close (SC-13c). */
function liveModal(): HTMLElement | null {
  return document.body.querySelector('.v-modal__overlay:not(.v-modal-leave-active)')
}

/** SC-13b: a dismissed VModal never leaves the DOM in happy-dom; it parks at leave-active. */
function modalDismissed(): boolean {
  return !!document.body.querySelector('.v-modal-leave-active')
}

function buttonWith(label: string): HTMLElement | undefined {
  return Array.from(host?.querySelectorAll<HTMLElement>('button') ?? []).find((b) =>
    b.textContent?.includes(label),
  )
}

/**
 * Which IconRating* component ICON_BY_ZONE picked. The three glyphs are
 * otherwise identical <svg fill="currentColor"> nodes with no class or id; their
 * viewBox is the only marker in the rendered DOM that tells them apart
 * (IconRatingFire.vue:6, IconRatingGood.vue:6, IconRatingConfused.vue:6).
 */
const RATING_ICON_VIEWBOX = {
  fire: '-26.76 -26.76 468.52 499.52',
  good: '-26.84 -26.84 501.01 494.91',
  confused: '13.18 -26.82 500.64 500.69',
} as const

function fbIconZone(row: HTMLElement): string {
  const vb = row.querySelector('svg')?.getAttribute('viewBox') ?? ''
  const hit = Object.entries(RATING_ICON_VIEWBOX).find(([, v]) => v === vb)
  return hit ? hit[0] : `unknown(${vb})`
}

beforeEach(() => {
  routeState.params = { id: 's1' }
  routeState.query = {}
  vi.mocked(mastersApi.getStudent).mockReset().mockResolvedValue(detail())
  push.mockReset()
  back.mockReset()
  info.mockReset()
})

afterEach(() => {
  app?.unmount()
  host?.remove()
  app = null
  host = null

  // A closed teleported overlay outlives unmount -- the <Transition> leave awaits
  // a transitionend happy-dom never fires. Without this the next test clicks a
  // corpse. SC-13. (.v-sheet__overlay is not reachable from this screen; only
  // VModal is used. Purging just what this screen can open.)
  document.body.querySelectorAll('.v-modal__overlay').forEach((el) => el.remove())

  vi.clearAllMocks()
})

describe('MasterStudentProfileView', () => {
  describe('state ladder', () => {
    it('shows the loader — and NOT the hero — while the fetch is in flight', async () => {
      vi.mocked(mastersApi.getStudent).mockReturnValue(
        new Promise(() => {}) as Promise<StudentDetailResponse>,
      )
      routeState.query = { name: 'Анна из списка' }
      mount()
      await flush()

      expect(host?.querySelector('.profile__state')).not.toBeNull()
      expect(host?.querySelector('.v-loader')).not.toBeNull()
      expect(host?.querySelector('.profile__hero')).toBeNull()
      // The ?name= "instant pre-fetch render" the script comment (.vue:117-120)
      // describes does not exist: the hero is gated behind `v-else` of the
      // loading branch, so the forwarded name paints nothing here.
      expect(text()).not.toContain('Анна из списка')
      // The chrome is outside the ladder and stays up throughout.
      expect(text()).toContain('Профиль ученика')
    })

    it('on failure: shows the error state with the screen fallback copy', async () => {
      vi.mocked(mastersApi.getStudent).mockRejectedValue(new Error('boom'))
      mount()
      await flush()

      expect(text()).toContain('Не удалось загрузить профиль')
      // .vue:137-139 is a bare `catch {}` -- the backend's own message is
      // SWALLOWED and replaced by this constant. Asserting 'boom' surfaced here
      // would be a lie (SC-05); asserting its ABSENCE pins the swallow.
      expect(text()).toContain('Попробуйте ещё раз')
      expect(text()).not.toContain('boom')
      expect(host?.querySelector('.profile__hero')).toBeNull()
    })

    it('error retry: «Повторить» re-runs the fetch with the same id and recovers', async () => {
      vi.mocked(mastersApi.getStudent).mockRejectedValueOnce(new Error('boom'))
      routeState.params = { id: 's-42' }
      mount()
      await flush()
      expect(text()).toContain('Не удалось загрузить профиль')

      vi.mocked(mastersApi.getStudent).mockResolvedValue(detail({ name: 'Борис Ли' }))
      buttonWith('Повторить')?.click()
      await flush()

      expect(text()).toContain('Борис Ли')
      expect(text()).not.toContain('Не удалось загрузить профиль')
      // load() re-reads route.params.id (.vue:136) -- both calls carry it.
      expect(vi.mocked(mastersApi.getStudent).mock.calls).toEqual([['s-42'], ['s-42']])
    })

    it('empty: a student with no check-ins and no feedbacks gets both empty lines, not zero sections', async () => {
      mount()
      await flush()

      expect(text()).toContain('Пока нет check-ins')
      expect(text()).toContain('Пока нет отзывов')
      expect(ciRows()).toHaveLength(0)
      expect(fbRows()).toHaveLength(0)
      // The section headings stay -- the empties live INSIDE the loaded content.
      expect(text()).toContain('Последние check-ins')
      expect(text()).toContain('Feedbacks')
      expect(showMorePills()).toHaveLength(0)
    })

    it('content: renders the name, stats and rows the API actually returned', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({
          name: 'Анна Кузнецова',
          practices_count: 12,
          hours: 18,
          recent_checkins: [checkin({ mood: 9, comment: 'Было классно' })],
          feedbacks: [feedback({ rating: 9, comment: 'Спасибо!' })],
        }),
      )
      mount()
      await flush()

      expect(host?.querySelector('.profile__hero-name')?.textContent).toBe('Анна Кузнецова')
      const stats = Array.from(host?.querySelectorAll('.v-stat') ?? [])
      expect(stats).toHaveLength(2)
      expect(stats[0]?.querySelector('.v-stat__value')?.textContent?.trim()).toBe('12')
      expect(stats[0]?.querySelector('.v-stat__label')?.textContent?.trim()).toBe('Практик')
      expect(stats[1]?.querySelector('.v-stat__value')?.textContent?.trim()).toBe('18')
      expect(stats[1]?.querySelector('.v-stat__label')?.textContent?.trim()).toBe('Часов')
      expect(text()).toContain('Было классно')
      expect(text()).toContain('Спасибо!')
      expect(text()).not.toContain('Пока нет check-ins')
      expect(text()).not.toContain('Пока нет отзывов')
    })
  })

  describe('the id plumbed from the route', () => {
    it('fetches the student named by route.params.id', async () => {
      routeState.params = { id: 's-42' }
      vi.mocked(mastersApi.getStudent).mockResolvedValue(detail({ name: 'Борис Ли' }))
      mount()
      await flush()

      expect(mastersApi.getStudent).toHaveBeenCalledWith('s-42')
      // ...and the fetched record is what paints -- the id is not merely passed.
      expect(host?.querySelector('.profile__hero-name')?.textContent).toBe('Борис Ли')
    })

    it('coerces a non-string param through String() before the request', async () => {
      // .vue:136 wraps the param in String(): vue-router types params as
      // string|string[], and an array id would otherwise reach the URL raw.
      routeState.params = { id: ['s7', 's8'] as unknown as string }
      mount()
      await flush()

      expect(mastersApi.getStudent).toHaveBeenCalledWith('s7,s8')
    })
  })

  describe('name (.vue:121-124) — the three-way fallback', () => {
    it('the fetched name wins over the ?name= the list forwarded', async () => {
      routeState.query = { name: 'Имя из списка' }
      vi.mocked(mastersApi.getStudent).mockResolvedValue(detail({ name: 'Имя из ответа' }))
      mount()
      await flush()

      expect(host?.querySelector('.profile__hero-name')?.textContent).toBe('Имя из ответа')
      expect(text()).not.toContain('Имя из списка')
    })

    it('an EMPTY name in the response falls back to ?name= — the only path that reaches it', async () => {
      routeState.query = { name: 'Имя из списка' }
      vi.mocked(mastersApi.getStudent).mockResolvedValue(detail({ name: '' }))
      mount()
      await flush()

      expect(host?.querySelector('.profile__hero-name')?.textContent).toBe('Имя из списка')
    })

    it('a repeated ?name= (string[]) is rejected, not joined — falls through to «Ученик»', async () => {
      // `typeof q === 'string' && q` (.vue:123): an array query is NOT a string,
      // so it is skipped rather than stringified into "a,b".
      routeState.query = { name: ['a', 'b'] }
      vi.mocked(mastersApi.getStudent).mockResolvedValue(detail({ name: '' }))
      mount()
      await flush()

      expect(host?.querySelector('.profile__hero-name')?.textContent).toBe('Ученик')
    })

    it('no name anywhere: the last-resort «Ученик» placeholder', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(detail({ name: '' }))
      mount()
      await flush()

      expect(host?.querySelector('.profile__hero-name')?.textContent).toBe('Ученик')
    })
  })

  describe('avatarUrl (.vue:125)', () => {
    it('renders the returned avatar as an <img>', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({ name: 'Анна Кузнецова', avatar_url: 'https://cdn.test/a.jpg' }),
      )
      mount()
      await flush()

      const img = host?.querySelector<HTMLImageElement>('.profile__hero-ava .v-avatar__img')
      expect(img).not.toBeNull()
      expect(img?.getAttribute('src')).toBe('https://cdn.test/a.jpg')
    })

    it('a null avatar_url becomes "" and degrades to initials, not a broken <img>', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({ name: 'Анна Кузнецова', avatar_url: null }),
      )
      mount()
      await flush()

      const ava = host?.querySelector('.profile__hero-ava')
      expect(ava?.querySelector('img')).toBeNull()
      expect(ava?.querySelector('.v-avatar__initials')?.textContent).toBe('АК')
    })
  })

  describe('practicesCount / hours (.vue:145-146)', () => {
    it('a missing detail renders 0, never blank or NaN', async () => {
      // The ?? 0 branch: reachable while detail is still null only via the
      // error->retry path in real use, but the derivation is the screen's own.
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({ practices_count: 0, hours: 0 }),
      )
      mount()
      await flush()

      const values = Array.from(host?.querySelectorAll('.v-stat__value') ?? []).map((n) =>
        n.textContent?.trim(),
      )
      expect(values).toEqual(['0', '0'])
    })
  })

  describe('checkinRows (.vue:154-160)', () => {
    it('a check-in with a comment shows the comment; the date is the fixture\'s, formatted short', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({
          recent_checkins: [checkin({ mood: 2, comment: 'Тяжело шло', created_at: '2026-09-12T23:30:00Z' })],
        }),
      )
      mount()
      await flush()

      const row = ciRows()[0]
      expect(row?.querySelector('.profile__ci-text')?.textContent).toBe('Тяжело шло')
      // formatShortDate in the default UTC tz: 12 Sept -> "12 сент." (format.ts:103-129).
      expect(row?.querySelector('.profile__ci-date')?.textContent).toBe('12 сент.')
    })

    it('a comment-less check-in falls back to the MOOD LABEL for its own score', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({
          recent_checkins: [
            checkin({ mood: 2, comment: null }),
            checkin({ mood: 5, comment: null }),
            checkin({ mood: 9, comment: null }),
          ],
        }),
      )
      mount()
      await flush()

      // moodZoneFromScore: 1-3 low / 4-7 mid / 8-10 high (displayHelpers.ts:69-73).
      // Scoped to .profile__ci-text: «Хорошо» is ALSO the `good` rating label, so
      // a host-wide toContain here would not prove which row said it.
      expect(ciRows().map((r) => r.querySelector('.profile__ci-text')?.textContent)).toEqual([
        'Не очень',
        'Нормально',
        'Хорошо',
      ])
    })

    it('an empty-string comment also falls back (falsy `||`, not a `??` on null only)', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({ recent_checkins: [checkin({ mood: 9, comment: '' })] }),
      )
      mount()
      await flush()

      expect(ciRows()[0]?.querySelector('.profile__ci-text')?.textContent).toBe('Хорошо')
    })

    it('each row gets its OWN mood face — the score is forwarded per row, not once', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({
          recent_checkins: [
            checkin({ mood: 1, comment: 'a' }),
            checkin({ mood: 5, comment: 'b' }),
            checkin({ mood: 10, comment: 'c' }),
          ],
        }),
      )
      mount()
      await flush()

      // MoodAvatar picks IconMoodLow/Mid/High off moodZoneFromScore. The three
      // assets are told apart in the DOM by: low's offset viewBox
      // (IconMoodLow.vue:10), and mid's <circle> eyes vs high's all-<path> face
      // (IconMoodMid.vue:12-13 / IconMoodHigh.vue) — they share "0 0 40 40".
      const faces = ciRows().map((r) => {
        const svg = r.querySelector('svg')!
        const vb = svg.getAttribute('viewBox') ?? ''
        if (vb.startsWith('4.85156')) return 'low'
        return svg.querySelector('circle') ? 'mid' : 'high'
      })
      expect(faces).toEqual(['low', 'mid', 'high'])
      // ...and the comments still line up with their own rows.
      expect(ciRows().map((r) => r.querySelector('.profile__ci-text')?.textContent)).toEqual([
        'a',
        'b',
        'c',
      ])
    })
  })

  describe('feedbackRows (.vue:162-173)', () => {
    it('maps rating -> label + icon across every zone boundary (3|4, 7|8)', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({
          feedbacks: [
            feedback({ rating: 3 }),
            feedback({ rating: 4 }),
            feedback({ rating: 7 }),
            feedback({ rating: 8 }),
          ],
        }),
      )
      mount()
      await flush()

      // Four boundary cases exceed PREVIEW_CAP=3, so the fourth is behind the
      // pill -- expand before asserting, or `8 -> Огонь!` is never rendered and
      // the case that matters most silently goes untested.
      showMorePills()[0]?.click()
      await flush()
      expect(fbRows()).toHaveLength(4)

      // ratingZoneFromScore: 1-3 confused / 4-7 good / 8-10 fire (displayHelpers.ts:76-80).
      expect(fbRows().map((r) => r.querySelector('.profile__fb-title')?.textContent)).toEqual([
        'Есть вопросы',
        'Хорошо',
        'Хорошо',
        'Огонь!',
      ])
      expect(fbRows().map(fbIconZone)).toEqual(['confused', 'good', 'good', 'fire'])
    })

    it('paints each icon with its zone colour token (RATING_ICON_COLOR, not RATING_COLOR)', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({ feedbacks: [feedback({ rating: 2 }), feedback({ rating: 5 }), feedback({ rating: 9 })] }),
      )
      mount()
      await flush()

      // displayHelpers.ts:110-114. The OTHER map (RATING_COLOR, :98-102) is the
      // analytics BAR palette -- peach/pink/blue -- and picking it here would be
      // a real regression that a label-only assertion would not catch.
      const colors = fbRows().map((r) =>
        r.querySelector<HTMLElement>('.profile__fb-ic')?.getAttribute('style'),
      )
      expect(colors).toEqual([
        'color: var(--velo-rating-confused);',
        'color: var(--velo-rating-good);',
        'color: var(--velo-rating-fire);',
      ])
    })

    it('renders the comment when there is one and omits the text node entirely when there is not', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({
          feedbacks: [
            feedback({ rating: 9, comment: 'Лучшая практика', created_at: '2026-05-01T08:00:00Z' }),
            feedback({ rating: 9, comment: null }),
          ],
        }),
      )
      mount()
      await flush()

      expect(fbRows()[0]?.querySelector('.profile__fb-text')?.textContent).toBe('Лучшая практика')
      // `v-if="fb.comment"` (.vue:75) -- '' from the ?? '' is falsy, so no empty node.
      expect(fbRows()[1]?.querySelector('.profile__fb-text')).toBeNull()
      // "1 мая" -- the leading zero was the format.ts:118 defect, fixed in №441.
      expect(fbRows()[0]?.querySelector('.profile__fb-date')?.textContent).toBe('1 мая')
    })

    // -----------------------------------------------------------------------
    // Was a pinned REAL BUG (found №440, FIXED №441) -- formatShortDate()'s
    // leading zero. It asked Intl for `day:'numeric'` but en-CA's format matcher
    // resolved the day+month skeleton to `MM-dd` -- resolvedOptions() really did
    // return `{month:'2-digit', day:'2-digit'}` -- so every day 1..9 rendered
    // zero-padded ("01 мая", "09 июня") against a docstring promising "9 июня".
    // Days 10..31 were correct, which is why it survived: a shared util across
    // 13 view/card surfaces, wrong for nine days of every month.
    //
    // The fix parses the day with Number() instead of rendering ICU's string,
    // so no locale or ICU build can pad it back. This test was written as a
    // TRIPWIRE against the broken output and is now flipped to the correct one
    // -- kept, not deleted, because it is the screen-level proof that the util
    // fix reaches rendered DOM. Unit-level boundaries live in format.test.ts.
    // -----------------------------------------------------------------------
    it('renders single-digit days with NO leading zero — the documented "9 июня" (format.ts:118, fixed №441)', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({
          recent_checkins: [checkin({ comment: 'x', created_at: '2026-06-09T10:00:00Z' })],
          feedbacks: [feedback({ rating: 5, created_at: '2026-01-05T10:00:00Z' })],
        }),
      )
      mount()
      await flush()

      expect(ciRows()[0]?.querySelector('.profile__ci-date')?.textContent).toBe('9 июня')
      expect(fbRows()[0]?.querySelector('.profile__fb-date')?.textContent).toBe('5 янв.')
    })
  })

  describe('the preview cap (.vue:178-188) — 3 each, independently expandable', () => {
    function overflowing() {
      return detail({
        recent_checkins: Array.from({ length: 5 }, (_, i) =>
          checkin({ mood: 5, comment: `ci-${i}` }),
        ),
        feedbacks: Array.from({ length: 5 }, (_, i) => feedback({ rating: 5, comment: `fb-${i}` })),
      })
    }

    it('caps BOTH lists at 3 and offers one pill per overflowing section', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(overflowing())
      mount()
      await flush()

      expect(ciRows()).toHaveLength(3)
      expect(fbRows()).toHaveLength(3)
      expect(text()).toContain('ci-2')
      expect(text()).not.toContain('ci-4')
      expect(text()).not.toContain('fb-4')
      expect(showMorePills()).toHaveLength(2)
      expect(showMorePills()[0]?.textContent?.trim()).toBe('посмотреть еще')
    })

    it('exactly 3 is NOT overflow — hiddenX is max(0, n-3), so no pill at the boundary', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(
        detail({
          recent_checkins: [checkin(), checkin(), checkin()],
          feedbacks: [feedback(), feedback(), feedback()],
        }),
      )
      mount()
      await flush()

      expect(ciRows()).toHaveLength(3)
      expect(fbRows()).toHaveLength(3)
      expect(showMorePills()).toHaveLength(0)
    })

    it('expanding check-ins reveals ONLY check-ins; the feedbacks stay capped', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(overflowing())
      mount()
      await flush()

      // Pill order is document order: check-ins (.vue:57) precedes feedbacks (.vue:78).
      showMorePills()[0]?.click()
      await flush()

      expect(ciRows()).toHaveLength(5)
      expect(text()).toContain('ci-4')
      expect(fbRows()).toHaveLength(3)
      expect(text()).not.toContain('fb-4')
      // The check-ins pill is gone; the feedbacks one remains.
      expect(showMorePills()).toHaveLength(1)
    })

    it('expanding feedbacks reveals ONLY feedbacks; the check-ins stay capped', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(overflowing())
      mount()
      await flush()

      showMorePills()[1]?.click()
      await flush()

      expect(fbRows()).toHaveLength(5)
      expect(text()).toContain('fb-4')
      expect(ciRows()).toHaveLength(3)
      expect(text()).not.toContain('ci-4')
      expect(showMorePills()).toHaveLength(1)
    })

    it('expanding is client-side over the already-loaded set — it never re-hits the network', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(overflowing())
      mount()
      await flush()

      showMorePills()[0]?.click()
      await flush()
      showMorePills()[0]?.click()
      await flush()

      expect(ciRows()).toHaveLength(5)
      expect(fbRows()).toHaveLength(5)
      expect(showMorePills()).toHaveLength(0)
      expect(mastersApi.getStudent).toHaveBeenCalledTimes(1)
    })
  })

  describe('navigation', () => {
    it('the header back button goes back — this screen never pushes a route', async () => {
      mount()
      await flush()

      host?.querySelector<HTMLElement>('[aria-label="Назад"]')?.click()
      await flush()

      expect(back).toHaveBeenCalledTimes(1)
      expect(push).not.toHaveBeenCalled()
    })
  })

  describe('the «Написать сообщение» CTA (E4 stub)', () => {
    it('opens the message sheet on document.body, addressed to THIS student', async () => {
      vi.mocked(mastersApi.getStudent).mockResolvedValue(detail({ name: 'Анна Кузнецова' }))
      mount()
      await flush()

      // Nothing teleported before the tap: VModal's v-if has never been true, so
      // this is a genuine absence, not an un-reaped corpse.
      expect(document.body.querySelector('.v-modal__overlay')).toBeNull()

      buttonWith('Написать сообщение')?.click()
      await flush()

      const modal = liveModal()
      expect(modal).not.toBeNull()
      // Proves :name="name" is bound to the computed, not to a placeholder.
      expect(modal?.querySelector('.send-msg__name')?.textContent).toBe('Анна Кузнецова')
    })

    it('«Отмена» dismisses the sheet', async () => {
      mount()
      await flush()

      buttonWith('Написать сообщение')?.click()
      await flush()
      // Pin the negative case first, or the assertion below could always-pass.
      expect(modalDismissed()).toBe(false)

      const cancel = Array.from(
        liveModal()?.querySelectorAll<HTMLElement>('button') ?? [],
      ).find((b) => b.textContent?.includes('Отмена'))
      cancel?.click()
      await flush()

      // SC-13b: the overlay is NOT removed -- it parks at leave-active awaiting a
      // transitionend happy-dom never fires. Asserting it is gone would fail
      // against a perfectly healthy screen.
      expect(modalDismissed()).toBe(true)
    })

    it('the CTA can never reach an API — messaging has no backend, so «Отправить» only toasts', async () => {
      mount()
      await flush()
      const callsAfterLoad = vi.mocked(mastersApi.getStudent).mock.calls.length

      buttonWith('Написать сообщение')?.click()
      await flush()
      const send = Array.from(liveModal()?.querySelectorAll<HTMLElement>('button') ?? []).find(
        (b) => b.textContent?.includes('Отправить'),
      )
      send?.click()
      await flush()

      // Verified at the source, not from the button's copy: SendMessageModal.vue:45-48.
      expect(info).toHaveBeenCalledWith('Сообщения пока недоступны')
      expect(vi.mocked(mastersApi.getStudent).mock.calls).toHaveLength(callsAfterLoad)
      expect(push).not.toHaveBeenCalled()
    })
  })
})

// =============================================================================
// NOT COVERED, deliberately
// =============================================================================
//
// - satisfaction_pct. It is in StudentDetailResponse (generated.ts:1200) and the
//   screen NEVER reads it -- the % stat card was removed in ПРОМТ №157 (.vue:41).
//   There is no derivation and no DOM to assert. Fixtures pass null to document
//   that the field is dead on this screen, not to test it.
//
// - The list->profile hand-off itself (?name= being SET). That is
//   MasterStudentsView's push, already covered by MasterStudentsView.test.ts
//   ('carrying the name forward in the query'). Here only the READ side is
//   asserted.
//
// - SendMessageModal's own internals: the textarea reset-on-open watch
//   (SendMessageModal.vue:38-43) and its VAvatar chip. They belong to that
//   component's test. This file asserts only what THIS screen owns of the sheet:
//   that the CTA opens it, with the right name, and that nothing reaches an API.
//
// - MoodAvatar's score->face mapping as a unit. Only the per-ROW forwarding is
//   asserted here (that the screen binds each row's own mood); the mapping
//   itself is displayHelpers' moodZoneFromScore, covered at the util layer.
//
// - route.params reactivity. The screen reads params only inside load()
//   (.vue:136) with no watcher, so there is nothing reactive to assert. Asserting
//   "changing the id refetches" would be a fiction; asserting "it does not" would
//   pin a static mock's behaviour, not the screen's. Noted in the banner instead.
// =============================================================================
