// =============================================================================
// VELO API -- Auto-generated TypeScript types
// =============================================================================
//
// DO NOT EDIT THIS FILE MANUALLY.
// Generated from OpenAPI schema by backend/scripts/generate_ts_types.py
// API version: 0.1.0
// =============================================================================

// -- Enums --------------------------------------------------------------------

/** Booking lifecycle statuses. */
export type BookingStatus = 'pending' | 'confirmed' | 'attended' | 'no_show' | 'cancelled'

/** Practice lifecycle statuses. */
export type PracticeStatus = 'draft' | 'scheduled' | 'live' | 'completed' | 'cancelled' | 'deleted'

/** Format of a practice session. NOTE: this is the *format*, not the content direction. The content direction (meditation / yoga / breathwork) lives in data.taxonomy. */
export type PracticeType = 'live' | 'series' | 'one_on_one' | 'replay'

/** User roles in the platform. USER: default role, can browse and book practices. MASTER: verified facilitator, can create and host practices. ADMIN: platform operator, can manage users and content. */
export type UserRole = 'user' | 'master' | 'admin'

/** Waitlist entry lifecycle statuses. */
export type WaitlistStatus = 'waiting' | 'notified' | 'converted' | 'left' | 'declined' | 'expired'

/** Withdrawal request lifecycle statuses. */
export type WithdrawalStatus = 'pending' | 'approved' | 'rejected'

// -- Interfaces ---------------------------------------------------------------

/** GET /api/v1/practices/{id}/ai-summary -- response body. practice_id: The practice this summary belongs to. summary: Generated text. Placeholder in Phase 9.1. is_mock: True when returned by MockAIService. generated_at: When the summary was produced. */
export interface AISummaryResponse {
  practice_id: string
  summary: string
  is_mock: boolean
  generated_at: string
}

/** Response for verify/reject actions. */
export interface AdminMasterActionResponse {
  user_id: string
  status: string
}

/** Single item in admin masters list -- user data + master status. CR-01: role narrowed from str to UserRole for type safety. */
export interface AdminMasterListItem {
  id: string
  telegram_id?: number | null
  first_name?: string | null
  last_name?: string | null
  avatar_url?: string | null
  role: UserRole
  is_active: boolean
  master_status: string
}

/** GET /api/v1/admin/stats -- response body. */
export interface AdminStatsResponse {
  users_count: number
  masters_count: number
  practices_count: number
  pending_verifications: number
}

/** Single withdrawal record for admin view. */
export interface AdminWithdrawalResponse {
  id: string
  user_id: string
  amount_cents: number
  fee_cents: number
  currency: string
  status: WithdrawalStatus
  payout_details: PayoutDetails
  admin_id?: string | null
  admin_note?: string | null
  approved_at?: string | null
  rejected_at?: string | null
  created_at: string
  updated_at?: string | null
}

/** POST /admin/withdrawals/{id}/approve -- optional admin note. */
export interface ApproveWithdrawalRequest {
  note?: string | null
}

/** A participant's PRE check-in as shown to the practice master. Minimal projection of Checkin (diary module): only what the master needs while preparing for the practice -- the mood score and the optional note. Exposed ONLY inside the master-only attendance view (see module docstring). */
export interface AttendanceCheckinResponse {
  mood: number
  comment: string | null
}

/** Single booking in attendance list. Enriched for the master's prep view (see module docstring): - user_display_name / user_avatar_url identify the participant. - checkin is their PRE check-in for this practice, or None if they did not leave one. */
export interface AttendanceItemResponse {
  booking_id: string
  user_id: string
  status: BookingStatus
  joined_at: string | null
  left_at: string | null
  user_display_name: string | null
  user_avatar_url: string | null
  checkin: AttendanceCheckinResponse | null
}

/** GET /api/v1/practices/{id}/attendance -- response. */
export interface AttendanceResponse {
  practice_id: string
  total: number
  attended: number
  no_show: number
  pending: number
  items: AttendanceItemResponse[]
}

/** POST /api/v1/auth/telegram — response body. */
export interface AuthResponse {
  user: UserResponse
  session_token: string
}

/** Booking with full practice details for single-booking view. Used by GET /api/v1/bookings/{id}. Returns the complete PracticeResponse so the frontend can render a full detail page (deep link from notification, master dashboard, etc.). */
export interface BookingDetailResponse {
  id: string
  practice_id: string
  user_id: string
  status: BookingStatus
  purchase_id: string | null
  cancelled_at: string | null
  cancellation_reason: string | null
  joined_at: string | null
  left_at: string | null
  created_at: string
  updated_at: string | null
  practice: PracticeResponse
}

/** Booking representation returned by endpoints. */
export interface BookingResponse {
  id: string
  practice_id: string
  user_id: string
  status: BookingStatus
  purchase_id: string | null
  cancelled_at: string | null
  cancellation_reason: string | null
  joined_at: string | null
  left_at: string | null
  created_at: string
  updated_at: string | null
}

/** Booking with lightweight practice summary for list views. Used by GET /api/v1/bookings/me. Gives the frontend enough data for card rendering (title, time, type, master) without N+1 calls. */
export interface BookingWithPracticeResponse {
  id: string
  practice_id: string
  user_id: string
  status: BookingStatus
  purchase_id: string | null
  cancelled_at: string | null
  cancellation_reason: string | null
  joined_at: string | null
  left_at: string | null
  created_at: string
  updated_at: string | null
  has_feedback: boolean
  has_checkin: boolean
  practice: PracticeSummary
}

/** DELETE /api/v1/bookings/{id} -- optional body. */
export interface CancelBookingRequest {
  reason?: string | null
}

/** POST /api/v1/practices/{id}/checkin body. */
export interface CheckinRequest {
  mood: number
  comment?: string | null
}

/** Single checkin in API responses. */
export interface CheckinResponse {
  id: string
  practice_id: string
  user_id: string
  booking_id: string
  mood: number
  comment: string | null
  check_type: string
  created_at: string
  updated_at: string | null
}

/** GET /api/v1/admin/consistency -- response body. */
export interface ConsistencyResponse {
  items: SemaphoreResult[]
  total: number
  ok_count: number
  alert_count: number
  run_at: string
}

/** POST /api/v1/bookings -- request body. Phase 6.7: optional promo_code for discount. Existing clients that omit promo_code continue to work unchanged. */
export interface CreateBookingRequest {
  practice_id: string
  promo_code?: string | null
}

/** POST /api/v1/admin/promos -- create a company promo code. Company promos: company pays for the discount from marketing budget. type=company and master_id=None are set automatically by the service. practice_id is always None (company promos are platform-wide). */
export interface CreateCompanyPromoRequest {
  code: string
  discount_percent: number
  max_uses?: number | null
  valid_from?: string | null
  valid_until?: string | null
  first_purchase_only?: boolean
}

/** POST /api/v1/diary body. */
export interface CreateDiaryEntryRequest {
  content: string
  title?: string | null
  mood?: number | null
  practice_id?: string | null
  entry_type?: string
  practice_phase?: string | null
}

/** POST /api/v1/masters/me/promos -- create a master promo code. Master promos: master absorbs the discount from their revenue. type and master_id are set automatically by the service layer. */
export interface CreateMasterPromoRequest {
  code: string
  discount_percent: number
  practice_id?: string | null
  max_uses?: number | null
  valid_from?: string | null
  valid_until?: string | null
  first_purchase_only?: boolean
}

/** POST /api/v1/practices -- request body. */
export interface CreatePracticeRequest {
  practice_type: string
  title: string
  description?: string | null
  what_to_prepare?: string | null
  contraindications?: string | null
  scheduled_at: string
  duration_minutes: number
  timezone: string
  max_participants?: number | null
  zoom_link?: string | null
  parent_practice_id?: string | null
  is_free?: boolean
  price_cents?: number
  currency?: string
  direction: string
  difficulty: string
  style?: string | null
}

/** User submits a new report. */
export interface CreateReportRequest {
  target_type: 'user' | 'master' | 'practice'
  target_id: string
  reason: string
}

/** POST /api/v1/masters/me/withdraw -- request body. amount_cents is the total withdrawal amount (fee deducted from it). Minimum enforced in service against settings.min_withdrawal_cents. */
export interface CreateWithdrawalRequest {
  amount_cents: number
}

/** Single diary entry in API responses. */
export interface DiaryEntryResponse {
  id: string
  user_id: string
  practice_id: string | null
  entry_type: string
  practice_phase: string | null
  title: string | null
  content: string
  mood: number | null
  is_deleted: boolean
  created_at: string
  updated_at: string | null
}

/** One event in the unified diary timeline (GET /api/v1/diary/feed). A denormalized projection of a DiaryEvent. `snapshot` is an open dict whose shape depends on `kind` -- the frontend reads the fields it needs per kind (practice card fields, mood, rating, content preview, etc.). Keeping it open here avoids a combinatorial explosion of per-kind schemas while the feed card design is still settling; the kinds themselves are a closed vocabulary (see kind). `source_type` + `source_id` let the card deep-link back to the originating object (practice detail now, replay archive later). */
export interface DiaryFeedItem {
  id: string
  kind: string
  occurred_at: string
  source_type: string
  source_id: string
  snapshot: Record<string, unknown>
  created_at: string
}

/** GET /api/v1/diary/feed -- cursor-paginated unified timeline. `next_cursor` is the occurred_at of the last item when a full page was returned (more may remain); null marks the end of the feed. The client passes it back as the `cursor` query param for the next page. */
export interface DiaryFeedResponse {
  items: DiaryFeedItem[]
  next_cursor: string | null
}

/** Admin dismisses a report. */
export interface DismissReportRequest {
  resolution_note?: string | null
}

/** Returned when user tries to create a duplicate report. Contains the existing report + a message suggesting to edit it. */
export interface ExistingReportResponse {
  message?: string
  report: ReportResponse
}

/** POST /api/v1/practices/{id}/feedback body. */
export interface FeedbackRequest {
  rating: number
  comment?: string | null
}

/** Single feedback in API responses. */
export interface FeedbackResponse {
  id: string
  practice_id: string
  user_id: string
  booking_id: string
  rating: number
  comment: string | null
  created_at: string
  updated_at: string | null
}

/** Step 2 of master application -- professional background. */
export interface MasterApplyExperience {
  methods: string[]
  experience_years: number
  bio?: string | null
  certifications?: string[]
}

/** Step 1 of master application -- basic profile. */
export interface MasterApplyProfile {
  display_name: string
  email?: string | null
  phone?: string | null
}

/** Combined 3-step master application form. */
export interface MasterApplyRequest {
  profile: MasterApplyProfile
  experience: MasterApplyExperience
  documents?: Record<string, unknown>[]
}

/** Response after submitting master application. */
export interface MasterApplyResponse {
  user_id: string
  status: string
  created_at: string
}

/** Public master profile representation. F7: payout field added -- extracted from data.get("payout"). None when master has not configured payout details yet. CR-01: min_withdrawal_cents and withdrawal_fee_cents added from settings so frontend does not hardcode financial constants. */
export interface MasterProfileResponse {
  user_id: string
  status: string
  display_name?: string | null
  bio?: string | null
  methods?: string[]
  experience_years?: number | null
  frozen_cents: number
  available_cents: number
  min_withdrawal_cents: number
  withdrawal_fee_cents: number
  payout?: PayoutDetails | null
  created_at: string
  updated_at?: string | null
}

/** User-facing master profile -- safe public subset + live counters. Returned by GET /api/v1/masters/{user_id} for any authenticated user. Used by the practice detail "Подробнее" link (frame 4) and the master profile screen (node 541:2065). SECURITY: this schema is the isolation boundary between public and private master data. It MUST NOT carry any financial fields (frozen_cents, available_cents, payout, withdrawal limits) or contact fields (email, phone). Only a verified master is exposed; pending / rejected / non-master ids resolve to 404 in the service (we do not reveal the existence of an unverified application). practices_count and reviews_count are LIVE ORM aggregates computed in the service, NOT read from the stale data.stats JSONB cache: practices_count -- Practice rows for this master, excluding draft and deleted statuses. reviews_count -- Feedback rows across all of this master's practices (every feedback, regardless of text). */
export interface MasterPublicResponse {
  user_id: string
  status: string
  display_name?: string | null
  bio?: string | null
  methods?: string[]
  experience_years?: number | null
  avatar_url?: string | null
  practices_count: number
  reviews_count: number
}

/** Check-in mood counts for a practice, bucketed by score range. mood is a 1..10 score; counts are grouped into three buckets: low = scores 1-3 mid = scores 4-7 high = scores 8-10 CR-01: fields are required (no default=0). This is a response-only schema -- the service always provides concrete values. */
export interface MoodDistribution {
  high: number
  mid: number
  low: number
}

/** User notification preferences (nested under credentials.notifications). All flags default to True. Used both as the typed shape returned inside UserResponse.notifications and as the optional update payload in UserUpdate (where every field is optional for partial updates). */
export interface NotificationSettings {
  push?: boolean
  practice_reminders?: boolean
  master_messages?: boolean
  support_messages?: boolean
}

/** Partial update for notification preferences. Every field optional: only the toggles the user flipped are sent. The service merges them onto the stored object so untouched flags are kept. */
export interface NotificationSettingsUpdate {
  push?: boolean | null
  practice_reminders?: boolean | null
  master_messages?: boolean | null
  support_messages?: boolean | null
}

/** Paginated list of withdrawals for admin. */
export interface PaginatedAdminWithdrawalsResponse {
  items: AdminWithdrawalResponse[]
  total: number
  limit: number
  offset: number
}

/** GET /api/v1/bookings/me -- paginated list. */
export interface PaginatedBookingsResponse {
  items: BookingWithPracticeResponse[]
  total: number
  limit: number
  offset: number
}

/** GET /api/v1/users/me/checkins -- paginated list. */
export interface PaginatedCheckinsResponse {
  items: CheckinResponse[]
  total: number
  limit: number
  offset: number
}

/** GET /api/v1/diary -- paginated list. */
export interface PaginatedDiaryEntriesResponse {
  items: DiaryEntryResponse[]
  total: number
  limit: number
  offset: number
}

/** GET /api/v1/users/me/feedbacks -- paginated list. */
export interface PaginatedFeedbacksResponse {
  items: FeedbackResponse[]
  total: number
  limit: number
  offset: number
}

/** GET /api/v1/admin/masters -- paginated master list. */
export interface PaginatedMastersResponse {
  items: AdminMasterListItem[]
  total: number
  limit: number
  offset: number
}

/** GET /api/v1/practices -- paginated public list. */
export interface PaginatedPracticesResponse {
  items: PracticeResponse[]
  total: number
  limit: number
  offset: number
}

/** Paginated list of promos. */
export interface PaginatedPromosResponse {
  items: PromoResponse[]
  total: number
  limit: number
  offset: number
}

/** GET /api/v1/purchases/me -- paginated list. */
export interface PaginatedPurchasesResponse {
  items: PurchaseWithPracticeResponse[]
  total: number
  limit: number
  offset: number
}

/** GET /api/v1/admin/reports -- paginated report list. */
export interface PaginatedReportsResponse {
  items: ReportResponse[]
  total: number
  limit: number
  offset: number
}

/** GET /api/v1/reports/me -- paginated list of user's own reports. */
export interface PaginatedUserReportsResponse {
  items: ReportResponse[]
  total: number
  limit: number
  offset: number
}

/** GET /api/v1/admin/users -- paginated user list. */
export interface PaginatedUsersResponse {
  items: UserResponse[]
  total: number
  limit: number
  offset: number
}

/** GET /api/v1/waitlist/me -- paginated list. */
export interface PaginatedWaitlistResponse {
  items: WaitlistWithPracticeResponse[]
  total: number
  limit: number
  offset: number
}

/** Paginated list of withdrawals. */
export interface PaginatedWithdrawalsResponse {
  items: WithdrawalResponse[]
  total: number
  limit: number
  offset: number
}

/** Payout details stored in MasterProfile.data.payout. CR-01: renamed from PayoutDetailsResponse -- this is an embedded object, not a top-level response. Name now matches frontend usage. */
export interface PayoutDetails {
  method: string
  details?: Record<string, unknown>
}

/** PATCH /api/v1/masters/me/payout -- request body. Flexible JSONB with minimal validation. The ``method`` field is required; ``details`` is freeform and depends on method: bank_transfer: {iban, bank_name, account_holder, swift} paypal: {email} revolut: {tag or phone} */
export interface PayoutDetailsUpdate {
  method: string
  details: Record<string, unknown>
}

/** GET /api/v1/practices/{id}/insights -- aggregated data. All data is anonymous: no user IDs, names, or comment texts. Only numeric distributions and counts. */
export interface PracticeInsightsResponse {
  practice_id: string
  participants: number
  checkins: MoodDistribution
  feedbacks: RatingDistribution
  comments_count: number
}

/** Practice representation returned by all endpoints. Calendar taxonomy (direction / style / difficulty) is surfaced here as top-level optional fields. The service extracts them from the data.taxonomy JSONB sandbox in practice_to_response(). They are optional because practices created before the Calendar iteration have an empty data sandbox (-> None), and model_validate() on a raw ORM object would not populate them otherwise. */
export interface PracticeResponse {
  id: string
  master_id: string
  master_name?: string | null
  master_avatar_url?: string | null
  master_methods?: string[]
  practice_type: PracticeType
  status: PracticeStatus
  title: string
  description: string | null
  what_to_prepare?: string | null
  contraindications?: string | null
  scheduled_at: string
  duration_minutes: number
  timezone: string
  max_participants: number | null
  current_participants: number
  zoom_link: string | null
  parent_practice_id: string | null
  is_free: boolean
  price_cents: number
  currency: string
  direction?: string | null
  style?: string | null
  difficulty?: string | null
  is_booked?: boolean
  is_paid?: boolean
  created_at: string
  updated_at: string | null
}

/** Compact practice representation for embedding in related responses. Used inside BookingWithPracticeResponse, WaitlistWithPracticeResponse, and PurchaseWithPracticeResponse to give the frontend enough data for list-view cards without a separate GET /practices/{id} call. CR-01: timezone added -- Practice ORM has timezone as NOT NULL, model_validate() picks it up automatically via from_attributes. Without this field, frontend fell back to Europe/Berlin for all practices regardless of actual timezone. status added -- lets list views (my bookings, dashboard nearest card) tell a live practice from a scheduled one without a separate GET /practices/{id} call. Picked up automatically via from_attributes (Practice ORM status is NOT NULL with a default). */
export interface PracticeSummary {
  id: string
  title: string
  practice_type: PracticeType
  status: PracticeStatus
  scheduled_at: string
  duration_minutes: number
  timezone: string
  master_id: string
  master_name?: string | null
  direction?: string | null
  is_free: boolean
  price_cents: number
  currency: string
}

/** POST /api/v1/practices/{id}/preview-purchase -- request body. Optional promo_code for pricing preview. */
export interface PreviewPurchaseRequest {
  promo_code?: string | null
}

/** Pricing preview before purchase -- no side effects. Shows what the user would pay with/without a promo code. */
export interface PreviewPurchaseResponse {
  practice_id: string
  amount_cents: number
  discount_cents: number
  paid_cents: number
  currency: string
  promo_code?: string | null
  promo_type?: string | null
  discount_percent?: number | null
}

/** Full promo record returned to master and admin. */
export interface PromoResponse {
  id: string
  code: string
  type: string
  master_id: string | null
  practice_id: string | null
  discount_percent: number
  max_uses: number | null
  used_count: number
  valid_from: string
  valid_until: string | null
  first_purchase_only: boolean
  is_active: boolean
  created_at: string
  updated_at: string | null
}

/** POST /api/v1/practices/{id}/purchase -- optional request body. promo_code is optional. If omitted or null, no promo is applied. Existing clients that send no body continue to work (all fields optional). */
export interface PurchaseRequest {
  promo_code?: string | null
}

/** Purchase details returned to client. Phase 6.7: added amount_cents, discount_cents, promo_id. Invariant: paid_cents = amount_cents - discount_cents. */
export interface PurchaseResponse {
  id: string
  user_id: string
  practice_id: string
  booking_id: string
  promo_id: string | null
  amount_cents: number
  discount_cents: number
  paid_cents: number
  currency: string
  commission_cents: number
  status: string
  completed_at: string | null
  created_at: string
  updated_at: string | null
}

/** Purchase with lightweight practice summary for list views. Used by GET /api/v1/purchases/me. Gives the frontend enough data for purchase history rendering (title, time, amount, status). */
export interface PurchaseWithPracticeResponse {
  id: string
  user_id: string
  practice_id: string
  booking_id: string
  promo_id: string | null
  amount_cents: number
  discount_cents: number
  paid_cents: number
  currency: string
  commission_cents: number
  status: string
  completed_at: string | null
  created_at: string
  updated_at: string | null
  practice: PracticeSummary
}

/** Feedback rating counts for a practice, bucketed by score range. rating is a 1..10 score; counts are grouped into three buckets: confused = scores 1-3 good = scores 4-7 fire = scores 8-10 CR-01: fields are required (no default=0). Same rationale as MoodDistribution above. */
export interface RatingDistribution {
  fire: number
  good: number
  confused: number
}

/** POST /admin/masters/{user_id}/reject -- request body. */
export interface RejectMasterRequest {
  reason: string
}

/** POST /admin/withdrawals/{id}/reject -- reason required. */
export interface RejectWithdrawalRequest {
  note: string
}

/** Single report -- returned to both user and admin. */
export interface ReportResponse {
  id: string
  reporter_id: string
  target_type: string
  target_id: string
  reason: string
  status: string
  resolved_by?: string | null
  resolution_note?: string | null
  resolved_at?: string | null
  created_at: string
  updated_at?: string | null
}

/** Admin resolves a report. */
export interface ResolveReportRequest {
  resolution_note: string
}

/** Tester role-switch capability (TEST-ONLY). Present in GET /users/me ONLY when settings.role_switch_enabled is True AND the user was seeded with credentials.role_switch.allowed_roles. The list is the set of roles this tester may switch their own account to via POST /users/me/role. Absent (null) for everyone else and on production. */
export interface RoleSwitchInfo {
  allowed_roles: UserRole[]
}

/** POST /api/v1/users/me/role — target role to switch into (TEST-only). Pydantic validates `role` against UserRole (user/master/admin); anything else is a 422. Whether the caller may actually switch to it is enforced in the service against their seeded allowed_roles set. */
export interface RoleSwitchRequest {
  role: UserRole
}

/** Single semaphore check result. name: machine-readable identifier (e.g. "1.1_bookings_eq_purchases"). category: one of 5 categories from VELO-Data-Consistency-Semaphores.md. status: OK if expected == actual, ALERT otherwise. expected: what the check expects (human-readable string or number). actual: what was found. details: optional dict with extra context (e.g. mismatched IDs). criticality: how severe an ALERT is. */
export interface SemaphoreResult {
  name: string
  category: string
  status: 'OK' | 'ALERT'
  expected: string
  actual: string
  details?: Record<string, unknown> | null
  criticality: 'critical' | 'warning' | 'info'
}

/** POST /api/v1/auth/telegram — request body. */
export interface TelegramAuthRequest {
  init_data: string
}

/** POST /api/v1/payments/topup -- request body. */
export interface TopupRequest {
  amount_cents: number
}

/** POST /api/v1/payments/topup -- response body. */
export interface TopupResponse {
  payment_id: string
  checkout_url: string
  amount_cents: number
  currency: string
}

/** PATCH /api/v1/diary/{id} body. All fields optional. Only provided fields are updated. */
export interface UpdateDiaryEntryRequest {
  content?: string | null
  title?: string | null
  mood?: number | null
  practice_id?: string | null
  entry_type?: string | null
  practice_phase?: string | null
  clear_mood?: boolean
  clear_title?: boolean
  clear_practice?: boolean
  clear_practice_phase?: boolean
}

/** PATCH /api/v1/practices/{id} -- request body. All fields optional. Only provided fields are updated. P-02: NOT NULL fields typed as X | None so that "not sent" works with exclude_unset. Service layer guards against explicit null. Calendar taxonomy (direction / difficulty / style) is optional here: "not sent" leaves the stored value untouched; if sent, it is validated and written into data.taxonomy by the service layer. */
export interface UpdatePracticeRequest {
  practice_type?: string | null
  title?: string | null
  description?: string | null
  what_to_prepare?: string | null
  contraindications?: string | null
  scheduled_at?: string | null
  duration_minutes?: number | null
  timezone?: string | null
  max_participants?: number | null
  zoom_link?: string | null
  parent_practice_id?: string | null
  status?: string | null
  is_free?: boolean | null
  price_cents?: number | null
  currency?: string | null
  direction?: string | null
  difficulty?: string | null
  style?: string | null
}

/** User edits their own pending report (reason only). */
export interface UpdateReportRequest {
  reason: string
}

/** User representation in API responses. onboarding_completed is derived from the credentials JSONB sandbox rather than a dedicated column (schema-on-read pattern). The raw credentials blob is pulled in only to compute that single boolean and is never serialized -- see _credentials below. Mechanism (kept deliberately simple -- one carrier field + one computed_field): _credentials is filled from the ORM object's `credentials` attribute via validation_alias under from_attributes, but excluded from output; onboarding_completed reads from it. */
export interface UserResponse {
  id: string
  telegram_id: number | null
  role: UserRole
  first_name: string | null
  last_name: string | null
  avatar_url: string | null
  timezone: string
  language: string
  is_active: boolean
  balance_cents: number
  created_at: string
  last_login_at: string | null
  onboarding_completed: boolean
  phone: string | null
  bio: string | null
  notifications: NotificationSettings
  role_switch: RoleSwitchInfo | null
}

/** GET /api/v1/bookings/me/stats -- current user's practice stats. Powers the two stat cards on the main profile screen: - practices_attended: how many practices the user actually attended. - hours_attended: total attended duration in hours (one decimal). */
export interface UserStatsResponse {
  practices_attended: number
  hours_attended: number
}

/** PATCH /api/v1/users/me — updatable profile fields. All fields are optional. Only provided fields are updated. avatar_url is excluded — managed by Telegram (future: Bot API). Empty strings are rejected (min_length=1). To clear a field, send null explicitly: {"last_name": null}. timezone and language are NOT NULL in DB — sending null for them is rejected by _reject_null_for_required_fields (mode="before"). onboarding_completed is written into the credentials JSONB by the service layer (not a column). null is meaningless here, so only true/false are accepted; "not sent" leaves it untouched. phone and bio also live in the credentials JSONB (schema-on-read, same pattern). Unlike the name fields, they allow an EMPTY STRING as a valid value: sending "" clears the field (stored as "" in credentials). They have no min_length for that reason -- only a max_length cap. "Not sent" leaves them untouched; null is treated the same as "not sent" by the service (dropped), so use "" (not null) to clear. */
export interface UserUpdate {
  first_name?: string | null
  last_name?: string | null
  timezone?: string | null
  language?: string | null
  onboarding_completed?: boolean | null
  phone?: string | null
  bio?: string | null
  notifications?: NotificationSettingsUpdate | null
}

/** POST /admin/masters/{user_id}/verify -- request body. */
export interface VerifyMasterRequest {
  notes?: string | null
}

/** Response from POST /waitlist/{id}/confirm. Returns both the converted waitlist entry and the new booking id. */
export interface WaitlistConfirmResponse {
  waitlist_entry: WaitlistEntryResponse
  booking_id: string
}

/** Waitlist entry returned by all endpoints. */
export interface WaitlistEntryResponse {
  id: string
  practice_id: string
  user_id: string
  position: number
  status: WaitlistStatus
  joined_at: string
  notified_at: string | null
  expires_at: string | null
  created_at: string
  updated_at: string | null
}

/** Waitlist entry with lightweight practice summary for list views. Used by GET /api/v1/waitlist/me. Gives the frontend enough data for card rendering (title, time, type, master) without N+1 calls. */
export interface WaitlistWithPracticeResponse {
  id: string
  practice_id: string
  user_id: string
  position: number
  status: WaitlistStatus
  joined_at: string
  notified_at: string | null
  expires_at: string | null
  created_at: string
  updated_at: string | null
  practice: PracticeSummary
}

/** Full withdrawal record returned to master and admin. */
export interface WithdrawalResponse {
  id: string
  user_id: string
  amount_cents: number
  fee_cents: number
  currency: string
  status: WithdrawalStatus
  payout_details: PayoutDetails
  admin_id: string | null
  admin_note: string | null
  approved_at: string | null
  rejected_at: string | null
  created_at: string
  updated_at: string | null
}
