// =============================================================================
// VELO Frontend -- LoginView Screen Tests (T8, ПРОМТ №431)
// =============================================================================
//
// Generated by probekit-screen-test. THIRD pattern: an inert stub. Read the
// scope note before extending this file.
//
// LoginView is DORMANT BY DESIGN -- an unlinked /auth/login route (G1=А,
// router/index.ts:496-502) that App.vue's stage machine never reaches; inside
// Telegram it is dead code. Every handler is a toast, not an endpoint: the
// Phase-A web-auth backend does not exist yet (Zod E17), so LoginView.vue:60-67
// deliberately surfaces «недоступно» instead of calling a missing route. This
// is the build-full-design-now rule in action -- the control exists, the toast
// admits it does nothing, and the gap is Zod's.
//
// So what is worth asserting here is NARROW and stated honestly: that the form
// renders, and that the inert handlers stay inert -- a toast, and specifically
// NOT a network call or a fake login. If someone later wires real auth in, the
// «submit does not authenticate» test below turns red, which is the point: it
// pins the stub as a stub until the backend lands, rather than pretending to
// test a login flow that does not exist (screen-antipatterns.md SC-09).
//
// No store, no API, no onMounted, no clock -- so no pinia, no api mock, no time
// pinning. Only vue-router and useToast need seams.
// =============================================================================

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { createApp, type App } from 'vue'
import LoginView from '@/views/auth/LoginView.vue'

const push = vi.fn()
const back = vi.fn()
vi.mock('vue-router', () => ({
  useRouter: () => ({ push, back }),
}))

const toastInfo = vi.fn()
const toastSuccess = vi.fn()
const toastError = vi.fn()
vi.mock('@/composables/useToast', () => ({
  useToast: () => ({ info: toastInfo, success: toastSuccess, error: toastError }),
}))

let app: App | null = null
let host: HTMLElement | null = null

function mount(): HTMLElement {
  host = document.createElement('div')
  document.body.appendChild(host)
  app = createApp(LoginView)
  app.mount(host)
  return host
}

function text(): string {
  return host?.textContent ?? ''
}

function buttonWith(label: string): HTMLButtonElement | undefined {
  return Array.from(host?.querySelectorAll('button') ?? []).find((b) =>
    b.textContent?.includes(label),
  )
}

beforeEach(() => {
  push.mockReset()
  back.mockReset()
  toastInfo.mockReset()
  toastSuccess.mockReset()
  toastError.mockReset()
})

afterEach(() => {
  app?.unmount()
  host?.remove()
  app = null
  host = null
  vi.clearAllMocks()
})

describe('LoginView (dormant Phase-A stub)', () => {
  describe('render', () => {
    it('renders the master-web login form', async () => {
      mount()

      expect(text()).toContain('С возвращением!')
      expect(text()).toContain('Вход для мастеров')
      expect(host?.querySelector('input[type="email"]')).not.toBeNull()
      expect(host?.querySelector('input[type="password"]')).not.toBeNull()
      expect(buttonWith('Войти')).toBeDefined()
    })

    it('offers the social options the design calls for', async () => {
      mount()

      expect(buttonWith('Войти через Google')).toBeDefined()
      expect(buttonWith('Войти через Apple')).toBeDefined()
    })

    it('binds the email and password fields', async () => {
      mount()

      const email = host?.querySelector<HTMLInputElement>('input[type="email"]')
      email!.value = 'master@example.com'
      email!.dispatchEvent(new Event('input'))

      expect(email!.value).toBe('master@example.com')
    })
  })

  describe('the stub stays a stub', () => {
    it('submit does NOT authenticate -- it admits the feature is missing', async () => {
      // The guard test for this screen. If a real auth call is ever wired in
      // without revisiting this file, this goes red on purpose.
      mount()
      buttonWith('Войти')?.click()

      expect(toastInfo).toHaveBeenCalledWith('Вход для мастеров появится в веб-версии')
      expect(push).not.toHaveBeenCalled()
      expect(toastSuccess).not.toHaveBeenCalled()
    })

    it('the social buttons are inert too, with their own copy', async () => {
      mount()
      buttonWith('Войти через Google')?.click()

      expect(toastInfo).toHaveBeenCalledWith('Вход через соцсети появится в веб-версии')
      expect(push).not.toHaveBeenCalled()
    })
  })

  describe('navigation (the only live behaviour on this screen)', () => {
    it('«Забыли пароль?» routes to the recovery screen', async () => {
      mount()
      buttonWith('Забыли пароль?')?.click()

      expect(push).toHaveBeenCalledWith({ name: 'auth-recover' })
    })

    it('the back pill goes back rather than pushing a route', async () => {
      mount()
      host?.querySelector<HTMLElement>('.auth__back')?.click()

      expect(back).toHaveBeenCalledTimes(1)
      expect(push).not.toHaveBeenCalled()
    })
  })
})
