#!/bin/bash

# ==============================================================================
# VELO Platform -- VPS Installation Script v2
# ==============================================================================
#
# WHAT THIS SCRIPT DOES:
#   1.  Pre-flight checks (OS, RAM, disk, DNS for 2 domains)
#   2.  Fix locale (en_US.UTF-8)
#   3.  Install system deps (Docker, Nginx, Certbot, UFW, git, dnsutils)
#   4.  Configure firewall (22/80/443 only)
#   5.  Create deploy user `velo` (non-root, docker group)
#   6.  Generate SSH deploy key -> add to GitHub Deploy Keys
#       (WITH write access -- required for bot to commit generated.ts)
#   7.  Clone repo via SSH alias `github.com-velo`
#   8.  Generate .env (random passwords) + prompt for Telegram bot creds
#   9.  Configure Nginx reverse proxy (vel-app.com, api.vel-app.com)
#   10. Obtain SSL certificates (Let's Encrypt) + auto-renewal cron
#   11. Configure git bot identity for auto-commit of generated.ts
#   12. Start Docker stack: build app -> up app+postgres+redis -> wait /ready
#       -> migrate -> gen-types -> bot-commit generated.ts -> build frontend
#       -> up frontend -> final /ready check
#   13. Create `velo` management script -> symlink /usr/local/bin/velo
#   14. Set up backup cron (4 AM daily, 7-day rotation)
#
# USAGE:
#   Run locally on the target VPS as root.
#   Do NOT pipe from curl -- the script needs an interactive TTY for the
#   GitHub deploy key prompt and Telegram credentials prompt.
#
# REQUIREMENTS:
#   - Ubuntu 22.04+ (fresh VPS, root access)
#   - Domain vel-app.com pointing to this server
#   - Subdomain api.vel-app.com (A record to server IP)
#   - GitHub repository aivis-one/velo exists
#   - You are logged in to GitHub as the owner of aivis-one/velo
#     (needed to add deploy key with write access)
#
# PHILOSOPHY (per Aivis):
#   The test server is a hypothesis sandbox -- it can be wiped and reinstalled
#   without notice. Production install will be a separate script derived from
#   this one with safety guards added; here we optimise for speed of iteration.
# ==============================================================================

set -euo pipefail

# ==============================================================================
# CONFIGURATION
# ==============================================================================

INSTALL_BASE="/opt/velo"
GITHUB_REPO="aivis-one/velo"
DEPLOY_USER="velo"
DOMAIN_FRONTEND="vel-app.com"
DOMAIN_API="api.vel-app.com"
APP_PORT="8000"
FRONTEND_PORT="3000"

# Bot identity used for auto-commit of generated.ts.
# This identity appears in `git log` when types are regenerated by `velo update`.
BOT_NAME="velo-bot"
BOT_EMAIL="bot@velo.local"

# SSH alias for GitHub. Repo URL becomes git@github.com-velo:OWNER/REPO.git
# so that this specific deploy key is always used, even if other keys exist.
SSH_HOST_ALIAS="github.com-velo"
DEPLOY_KEY="/root/.ssh/id_ed25519_velo_deploy"

# ==============================================================================
# COLORS & LOGGING
# ==============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()     { echo -e "${GREEN}[$(date +'%H:%M:%S')]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}✓${NC} $1"; }
section() { echo -e "\n${CYAN}${BOLD}=== $1 ===${NC}\n"; }

# Trap any error to a clear message. set -e propagates non-zero exit codes,
# this handler decorates them so the failure point is obvious in output.
handle_error() {
    echo -e "\n${RED}[ERROR]${NC} Installation failed at line ${1}."
    echo "Check output above for details."
    exit 1
}
trap 'handle_error ${LINENO}' ERR

# ==============================================================================
# PRE-FLIGHT CHECKS
# ==============================================================================

section "Pre-flight Checks"

if [ "$(id -u)" -ne 0 ]; then
    error "This script must be run as root. Try: sudo $0"
fi

if [ ! -f /etc/os-release ]; then
    error "Cannot detect OS (no /etc/os-release)"
fi
. /etc/os-release
if [ "$ID" != "ubuntu" ]; then
    warn "Tested on Ubuntu. Detected: $ID. Continuing anyway."
fi

# Disk -- recommended 10GB free in /opt. Warn only; the operator decides.
# (Old velo behaviour. Hard error would block legitimate test-server use.)
DISK_FREE_GB=$(df -BG /opt 2>/dev/null | tail -1 | awk '{print $4}' | tr -d 'G')
if [ -z "$DISK_FREE_GB" ]; then
    # /opt may not exist yet on a truly fresh server; fall back to /.
    DISK_FREE_GB=$(df -BG / | tail -1 | awk '{print $4}' | tr -d 'G')
fi
if [ "$DISK_FREE_GB" -lt 10 ]; then
    warn "Low disk: ${DISK_FREE_GB}GB free (recommended >=10GB)"
else
    success "Disk: ${DISK_FREE_GB}GB free"
fi

# RAM -- recommended 2GB. Warn only.
RAM_TOTAL_MB=$(free -m | awk '/Mem:/ {print $2}')
if [ "$RAM_TOTAL_MB" -lt 2000 ]; then
    warn "Low RAM: ${RAM_TOTAL_MB}MB (recommended >=2000MB)"
else
    success "RAM: ${RAM_TOTAL_MB}MB total"
fi

# DNS -- both domains must resolve to this server. We don't fail on mismatch
# (the user may be testing from a different IP, or DNS may be propagating),
# but we log clearly so the certbot step doesn't surprise us.
SERVER_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || echo "unknown")
info "Server IP: $SERVER_IP"

# dig might not be installed yet; fall back to host or getent.
resolve_a() {
    local DOMAIN="$1"
    if command -v dig &>/dev/null; then
        dig +short A "$DOMAIN" | head -1
    elif command -v host &>/dev/null; then
        host -t A "$DOMAIN" 2>/dev/null | awk '/has address/{print $4; exit}'
    else
        getent hosts "$DOMAIN" | awk '{print $1; exit}'
    fi
}

for D in "$DOMAIN_FRONTEND" "$DOMAIN_API"; do
    RESOLVED=$(resolve_a "$D" 2>/dev/null || echo "")
    if [ -z "$RESOLVED" ]; then
        warn "$D does not resolve (DNS not propagated yet?)"
    elif [ "$RESOLVED" != "$SERVER_IP" ]; then
        warn "$D resolves to $RESOLVED but server IP is $SERVER_IP"
    else
        success "$D -> $RESOLVED (matches)"
    fi
done

# ==============================================================================
# PREVIOUS INSTALLATION CHECK
# ==============================================================================
#
# Test-server philosophy: the box is a hypothesis sandbox. A reinstall must
# fully reset to a known-good state, otherwise stale data from a previous run
# (DB volumes with old passwords, dangling nginx config, broken cron entries)
# silently breaks the new install in confusing ways.
#
# What we wipe:
#   - Docker containers + volumes (-v) -- volumes carry DB data with the OLD
#     POSTGRES_PASSWORD; without -v the fresh app container can't auth.
#   - $INSTALL_BASE entirely -- repo, vite.env, backups, manage script.
#   - /usr/local/bin/velo symlink.
#   - Nginx site config -- otherwise a future install with different domains
#     would conflict with the leftover server_name.
#   - Backup cron entry -- otherwise cron keeps trying to call a deleted
#     management script every night.
#
# What we PRESERVE:
#   - SSH deploy key (/root/.ssh/id_ed25519_velo_deploy) -- so the operator
#     doesn't have to re-add it to GitHub on every reinstall.
#   - SSL certificates (/etc/letsencrypt/live/) -- Let's Encrypt enforces 5
#     issuances per domain per week; sneeze too many reinstalls and we get
#     locked out. Certbot will reuse the existing cert if it's still valid.
# ==============================================================================

if [ -d "$INSTALL_BASE/repo" ] || [ -L /usr/local/bin/velo ]; then
    warn "Found existing installation at $INSTALL_BASE"
    echo ""
    read -rp "Remove existing installation and start fresh? (y/n): " -n 1 < /dev/tty
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        error "Cannot proceed with existing installation. Exiting."
    fi

    # 1. Stop containers and remove volumes. -v is critical: without it the
    #    Postgres volume survives with the OLD password, and the freshly-
    #    generated .env can't authenticate.
    if [ -f "$INSTALL_BASE/repo/docker-compose.yml" ]; then
        log "Stopping containers and removing volumes..."
        (cd "$INSTALL_BASE/repo" && docker compose down -v 2>/dev/null) || true
    fi

    # 2. Remove installation tree + management symlink.
    log "Removing installation files..."
    rm -rf "$INSTALL_BASE"
    rm -f /usr/local/bin/velo

    # 3. Remove nginx site (cert files preserved -- see header comment).
    if [ -f /etc/nginx/sites-available/velo ] || [ -L /etc/nginx/sites-enabled/velo ]; then
        log "Removing nginx site config..."
        rm -f /etc/nginx/sites-enabled/velo
        rm -f /etc/nginx/sites-available/velo
        # Reload only if nginx is running and config is valid (it should be,
        # since we just removed a site -- but be defensive).
        if systemctl is-active --quiet nginx; then
            nginx -t > /dev/null 2>&1 && systemctl reload nginx 2>/dev/null || true
        fi
    fi

    # 4. Remove backup cron entry. Filter out any line referring to "velo backup"
    #    and write the result back. If crontab is empty afterwards, crontab -
    #    accepts that fine.
    if crontab -l 2>/dev/null | grep -q "velo backup"; then
        log "Removing backup cron entry..."
        crontab -l 2>/dev/null | grep -v "velo backup" | crontab - 2>/dev/null || true
    fi

    success "Previous installation removed (SSH key + SSL certs preserved)"
fi

# ==============================================================================
# LOCALE
# ==============================================================================

section "Locale"

if ! locale -a 2>/dev/null | grep -qi "en_US.utf8"; then
    log "Generating en_US.UTF-8 locale..."
    apt-get update -qq
    apt-get install -y -qq locales > /dev/null
    locale-gen en_US.UTF-8 > /dev/null
    update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
fi
success "Locale: en_US.UTF-8"

# ==============================================================================
# SYSTEM DEPENDENCIES
# ==============================================================================

section "System Dependencies"

apt-get update -qq
apt-get install -y -qq \
    ca-certificates \
    curl \
    gnupg \
    git \
    ufw \
    dnsutils \
    cron \
    > /dev/null
success "Base packages installed"

# -- Docker (official repo, not Ubuntu's docker.io) --
if ! command -v docker &>/dev/null; then
    log "Installing Docker..."
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update -qq
    apt-get install -y -qq \
        docker-ce docker-ce-cli containerd.io \
        docker-buildx-plugin docker-compose-plugin > /dev/null
    systemctl enable --now docker
fi
success "Docker: $(docker --version | cut -d, -f1)"

# -- Nginx + Certbot --
if ! command -v nginx &>/dev/null; then
    apt-get install -y -qq nginx > /dev/null
    systemctl enable --now nginx
fi
success "Nginx: $(nginx -v 2>&1 | cut -d/ -f2)"

if ! command -v certbot &>/dev/null; then
    apt-get install -y -qq certbot python3-certbot-nginx > /dev/null
fi
success "Certbot installed"

# ==============================================================================
# FIREWALL
# ==============================================================================

section "Firewall"

ufw default deny incoming > /dev/null
ufw default allow outgoing > /dev/null
ufw allow 22/tcp > /dev/null    # SSH
ufw allow 80/tcp > /dev/null    # HTTP (certbot challenge + redirect)
ufw allow 443/tcp > /dev/null   # HTTPS
echo "y" | ufw enable > /dev/null 2>&1 || true
success "Firewall: 22/80/443 only"

# ==============================================================================
# DEPLOY USER
# ==============================================================================

section "Deploy User"

if id "$DEPLOY_USER" &>/dev/null; then
    success "User '$DEPLOY_USER' already exists"
else
    useradd -m -s /bin/bash "$DEPLOY_USER"
    success "User '$DEPLOY_USER' created"
fi
usermod -aG docker "$DEPLOY_USER"
success "User '$DEPLOY_USER' in docker group"

# ==============================================================================
# SSH DEPLOY KEY + REPO CLONE
# ==============================================================================

section "SSH Deploy Key & Repository"

mkdir -p /root/.ssh
chmod 700 /root/.ssh

# Trust github.com host fingerprint.
if ! grep -q "github.com" /root/.ssh/known_hosts 2>/dev/null; then
    ssh-keyscan -H github.com >> /root/.ssh/known_hosts 2>/dev/null
fi

# Generate deploy key.
if [ ! -f "$DEPLOY_KEY" ]; then
    ssh-keygen -t ed25519 -C "velo-deploy@$(hostname)" -f "$DEPLOY_KEY" -N "" > /dev/null
    success "Deploy key generated: $DEPLOY_KEY"
else
    success "Deploy key already exists"
fi

# SSH config: bind the deploy key to a dedicated host alias so commands like
# `git push origin release` automatically pick the right key, no GIT_SSH_COMMAND
# env-var dance needed. IdentitiesOnly=yes prevents ssh-agent fallback to
# other (potentially wrong) keys.
if ! grep -q "Host $SSH_HOST_ALIAS" /root/.ssh/config 2>/dev/null; then
    cat >> /root/.ssh/config <<EOF

# VELO Deploy Key (added by install_velo.sh)
Host $SSH_HOST_ALIAS
    HostName github.com
    User git
    IdentityFile $DEPLOY_KEY
    IdentitiesOnly yes
EOF
    chmod 600 /root/.ssh/config
fi

echo ""
echo -e "${YELLOW}${BOLD}ACTION REQUIRED:${NC}"
echo "Add this deploy key to GitHub repo $GITHUB_REPO:"
echo ""
echo "  1. Open: https://github.com/$GITHUB_REPO/settings/keys"
echo "  2. Click 'Add deploy key'"
echo "  3. Title: $(hostname)-deploy"
echo "  4. Paste the key below"
echo -e "  5. ${BOLD}${RED}IMPORTANT: tick the 'Allow write access' checkbox${NC}"
echo "     (velo-bot needs to push regenerated generated.ts on each update)"
echo ""
echo -e "${CYAN}"
cat "${DEPLOY_KEY}.pub"
echo -e "${NC}"
echo "Press ENTER after adding the deploy key (with write access)..."
read -r < /dev/tty

# Verify SSH connection works. We deliberately don't fail the whole install
# if it doesn't -- the user might have a slow network or DNS issue. The
# git clone right after will fail loudly anyway if auth is broken.
if ssh -T "$SSH_HOST_ALIAS" 2>&1 | grep -q "successfully authenticated"; then
    success "GitHub SSH connection verified"
else
    warn "Could not verify GitHub SSH connection. Proceeding anyway."
fi

# Clone repo via SSH alias.
mkdir -p "$INSTALL_BASE"
if [ -d "$INSTALL_BASE/repo/.git" ]; then
    success "Repo already cloned at $INSTALL_BASE/repo (skipping)"
else
    cd "$INSTALL_BASE"
    git clone "git@${SSH_HOST_ALIAS}:${GITHUB_REPO}.git" repo
    success "Repository cloned to $INSTALL_BASE/repo"
fi
chown -R root:root "$INSTALL_BASE"

# ==============================================================================
# ENV GENERATION
# ==============================================================================

section "Environment Configuration"

ENV_FILE="$INSTALL_BASE/repo/backend/.env"
VITE_ENV_FILE="$INSTALL_BASE/vite.env"

if [ -f "$ENV_FILE" ] && [ -f "$VITE_ENV_FILE" ]; then
    success ".env and vite.env already exist (skipping)"
else
    log "Generating .env with secure passwords..."

    # 25-char random passwords for PG/Redis. token_urlsafe(64) for SECRET_KEY
    # gives ~86 chars which is plenty for HS256/HS512 signing.
    PG_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)
    REDIS_PASSWORD=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-25)
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(64))")

    echo ""
    echo -e "${CYAN}${BOLD}Telegram Bot${NC}"
    echo "Get token from @BotFather in Telegram."
    echo "Leave empty to skip (you can add later in backend/.env)."
    echo ""
    read -rp "TELEGRAM_BOT_TOKEN: " TELEGRAM_BOT_TOKEN < /dev/tty
    read -rp "TELEGRAM_BOT_USERNAME (e.g. velo_testbot): " TELEGRAM_BOT_USERNAME < /dev/tty
    TELEGRAM_BOT_USERNAME="${TELEGRAM_BOT_USERNAME#@}"
    echo ""

    cat > "$ENV_FILE" <<EOF
# ===========================================================================
# VELO Backend -- Test Environment
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Server: $(hostname) (${SERVER_IP})
# ===========================================================================

# --- Application ---
APP_ENV=production
LOG_LEVEL=INFO

# --- Security ---
# Auto-generated. NEVER commit this file.
SECRET_KEY=${SECRET_KEY}

# --- Database (PostgreSQL) ---
# Credentials match POSTGRES_* used by Docker to provision the DB.
DATABASE_URL=postgresql+asyncpg://velo:${PG_PASSWORD}@postgres:5432/velo
POSTGRES_DB=velo
POSTGRES_USER=velo
POSTGRES_PASSWORD=${PG_PASSWORD}

# --- Redis ---
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
REDIS_PASSWORD=${REDIS_PASSWORD}

# --- CORS ---
CORS_ORIGINS=https://${DOMAIN_FRONTEND}

# --- Telegram ---
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}

# --- Session ---
SESSION_TTL_DAYS=30

# --- Stripe (placeholders, replace before going live) ---
STRIPE_SECRET_KEY=TEST
STRIPE_WEBHOOK_SECRET=TEST
STRIPE_PUBLISHABLE_KEY=TEST
STRIPE_SUCCESS_URL=TEST
STRIPE_CANCEL_URL=TEST
EOF
    chmod 600 "$ENV_FILE"
    success ".env generated"

    # vite.env -- frontend build-time args. Sourced by start_stack() and
    # velo update so the same values are used on every rebuild.
    cat > "$VITE_ENV_FILE" <<EOF
VITE_API_BASE_URL=https://${DOMAIN_API}
VITE_TELEGRAM_BOT_URL=https://t.me/${TELEGRAM_BOT_USERNAME}
EOF
    success "vite.env saved at $VITE_ENV_FILE"
fi

# ==============================================================================
# NGINX (HTTP only -- certbot needs port 80 first)
# ==============================================================================

section "Nginx (HTTP)"

cat > /etc/nginx/sites-available/velo <<'NGINX_HTTP_EOF'
# VELO -- Nginx reverse proxy (HTTP, pre-certbot)
# Frontend -> 127.0.0.1:3000
# API      -> 127.0.0.1:8000

server {
    listen 80;
    server_name vel-app.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name api.vel-app.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
NGINX_HTTP_EOF

ln -sf /etc/nginx/sites-available/velo /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
mkdir -p /var/www/certbot
nginx -t > /dev/null
systemctl reload nginx
success "Nginx HTTP config active"

# ==============================================================================
# SSL CERTIFICATES
# ==============================================================================

section "SSL Certificates"

# certonly with --webroot -- doesn't touch our nginx config, just drops the
# challenge files and validates. We rewrite the nginx config to HTTPS in the
# next step using the issued certs.
if certbot certonly \
    --webroot \
    --webroot-path=/var/www/certbot \
    -d "$DOMAIN_FRONTEND" \
    -d "$DOMAIN_API" \
    --non-interactive \
    --agree-tos \
    --email "admin@$DOMAIN_FRONTEND" \
    --no-eff-email; then
    success "SSL certificate obtained"
    SSL_OK=1
else
    warn "SSL setup failed -- keeping HTTP-only config"
    warn "Retry manually: certbot certonly --webroot --webroot-path=/var/www/certbot -d $DOMAIN_FRONTEND -d $DOMAIN_API"
    SSL_OK=0
fi

# Rewrite nginx config to HTTPS only if cert was obtained.
if [ "$SSL_OK" = "1" ]; then
    cat > /etc/nginx/sites-available/velo <<'NGINX_HTTPS_EOF'
# VELO -- Nginx reverse proxy (HTTPS)
# vel-app.com     -> frontend (127.0.0.1:3000)
# api.vel-app.com -> backend  (127.0.0.1:8000)

# -- vel-app.com: HTTP -> HTTPS --
server {
    listen 80;
    server_name vel-app.com;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
}

# -- vel-app.com: HTTPS -> frontend --
server {
    listen 443 ssl http2;
    server_name vel-app.com;

    ssl_certificate     /etc/letsencrypt/live/vel-app.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vel-app.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# -- api.vel-app.com: HTTP -> HTTPS --
server {
    listen 80;
    server_name api.vel-app.com;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
}

# -- api.vel-app.com: HTTPS -> backend --
server {
    listen 443 ssl http2;
    server_name api.vel-app.com;

    ssl_certificate     /etc/letsencrypt/live/vel-app.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vel-app.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
NGINX_HTTPS_EOF
    nginx -t > /dev/null && systemctl reload nginx
    success "Nginx HTTPS config active"

    # Auto-renewal cron at 3 AM daily.
    if ! crontab -l 2>/dev/null | grep -q "certbot renew"; then
        (crontab -l 2>/dev/null; \
         echo "0 3 * * * certbot renew --quiet --post-hook 'systemctl reload nginx'") | crontab -
        success "SSL auto-renewal cron added (3 AM daily)"
    fi
fi

# ==============================================================================
# GIT BOT IDENTITY
# ==============================================================================
#
# Used by `velo update` when it auto-commits regenerated frontend/src/api/
# generated.ts. Setting the identity on the repo (not globally) avoids
# polluting other repos on the same machine.
# ==============================================================================

section "Git Bot Identity"

cd "$INSTALL_BASE/repo"
git config user.name "$BOT_NAME"
git config user.email "$BOT_EMAIL"
# safe.directory is required for git 2.35+ when the working tree is owned
# by root and operations run from a different uid context (e.g. through
# the velo wrapper invoked from a non-root shell).
git config --global --add safe.directory "$INSTALL_BASE/repo"
success "Git identity: $BOT_NAME <$BOT_EMAIL>"

# ==============================================================================
# DOCKER STACK -- INITIAL STARTUP
# ==============================================================================
#
# Order:
#   1. Build backend image.
#   2. Up backend + postgres + redis (frontend deferred -- needs generated.ts).
#   3. Wait for /ready (returns 503 until DB+Redis are reachable).
#   4. Run alembic migrations.
#   5. Fetch /openapi.json -> regenerate generated.ts.
#   6. If generated.ts changed: bot-commit and push (so git == reality).
#   7. Build frontend image (now with up-to-date types).
#   8. Up frontend.
#   9. Final /ready check.
# ==============================================================================

section "Docker Stack"

cd "$INSTALL_BASE/repo"

# Source vite.env so VITE_* are available to the frontend builder stage.
set -a
# shellcheck disable=SC1090
source "$VITE_ENV_FILE"
set +a

log "Building backend image..."
docker compose build app

log "Starting backend + postgres + redis..."
docker compose up -d app postgres redis

# Wait for /ready (503 -> 200). 18 * 5 = 90s max -- DB needs to come up,
# migrations have not run yet so /ready may flap until tables exist; that's
# why we wait on /health-ish behaviour first then migrate then re-check.
log "Waiting for backend /ready..."
for i in $(seq 1 18); do
    HTTP=$(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:${APP_PORT}/health" 2>/dev/null || echo "000")
    if [ "$HTTP" = "200" ]; then
        # /health gives 200 even if degraded; just means the process is alive.
        # We accept it because /ready is gated on migrations next.
        break
    fi
    if [ "$i" = "18" ]; then
        error "Backend did not respond within 90s. Check: docker compose logs app"
    fi
    echo -n "."
    sleep 5
done
echo ""
success "Backend process is up"

log "Running database migrations..."
docker compose exec -T app python -m alembic upgrade head
success "Migrations applied"

log "Regenerating frontend types from live OpenAPI..."
curl -sf "http://127.0.0.1:${APP_PORT}/openapi.json" > /tmp/openapi.json || {
    error "Cannot fetch /openapi.json from backend"
}
python3 "$INSTALL_BASE/repo/backend/scripts/generate_ts_types.py" \
    /tmp/openapi.json \
    "$INSTALL_BASE/repo/frontend/src/api/generated.ts"
rm -f /tmp/openapi.json

# Bot-commit if generated.ts changed. On a fresh install the file is either
# unchanged (matches what's in git) or different (drift from prior dev).
# Either way -- never carry a local diff past this point.
if [ -n "$(git -C "$INSTALL_BASE/repo" status --porcelain frontend/src/api/generated.ts)" ]; then
    log "generated.ts drifted from git -- committing as $BOT_NAME"
    git -C "$INSTALL_BASE/repo" add frontend/src/api/generated.ts
    git -C "$INSTALL_BASE/repo" commit -m \
"chore(types): regenerate generated.ts (install)

Triggered by install_velo.sh on $(hostname)."
    # Push with single retry on rebase conflict (rare on a fresh install,
    # but possible if a parallel dev pushed something between the clone
    # above and this commit).
    PUSH_OK=0
    for attempt in 1 2; do
        if git -C "$INSTALL_BASE/repo" push origin HEAD; then
            PUSH_OK=1; break
        fi
        if [ "$attempt" = "1" ]; then
            warn "Push failed (probably parallel push). Rebasing and retrying..."
            git -C "$INSTALL_BASE/repo" pull --rebase origin "$(git -C "$INSTALL_BASE/repo" branch --show-current)" || break
        fi
    done
    if [ "$PUSH_OK" = "1" ]; then
        success "Bot pushed regenerated types"
    else
        warn "Bot commit exists locally but was not pushed -- resolve later"
    fi
else
    success "generated.ts matches git (no drift)"
fi

log "Building frontend image..."
docker compose build frontend

log "Starting frontend..."
docker compose up -d frontend

# Final readiness check: /ready returns 503 if degraded, 200 if all-clear.
log "Waiting for /ready..."
for i in $(seq 1 12); do
    if curl -sf "http://127.0.0.1:${APP_PORT}/ready" > /dev/null 2>&1; then
        success "/ready is 200"
        break
    fi
    if [ "$i" = "12" ]; then
        warn "/ready did not return 200 within 60s"
        warn "Check: velo logs app   |   velo status"
    fi
    echo -n "."
    sleep 5
done
echo ""

# ==============================================================================
# MANAGEMENT SCRIPT
# ==============================================================================

section "Management Script"

MANAGE_SCRIPT="$INSTALL_BASE/velo"

cat > "$MANAGE_SCRIPT" <<MANAGE_EOF
#!/bin/bash
# ==============================================================================
# velo -- VELO Platform Management Script v2
# Generated by install_velo.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# ==============================================================================

INSTALL_BASE="$INSTALL_BASE"
COMPOSE_DIR="$INSTALL_BASE/repo"
VITE_ENV_FILE="$VITE_ENV_FILE"
DOMAIN_FRONTEND="$DOMAIN_FRONTEND"
DOMAIN_API="$DOMAIN_API"
APP_PORT="$APP_PORT"
DEPLOY_KEY="$DEPLOY_KEY"
SSH_HOST_ALIAS="$SSH_HOST_ALIAS"
BOT_NAME="$BOT_NAME"
BOT_EMAIL="$BOT_EMAIL"
GITHUB_REPO="$GITHUB_REPO"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

cd_compose() {
    cd "\$COMPOSE_DIR" || { echo -e "\${RED}ERROR: \$COMPOSE_DIR not found\${NC}"; exit 1; }
}

# Source vite.env when frontend build is involved -- VITE_* must be on the
# environment for docker compose build to substitute them via build args.
source_vite_env() {
    if [ -f "\$VITE_ENV_FILE" ]; then
        set -a
        # shellcheck disable=SC1090
        source "\$VITE_ENV_FILE"
        set +a
    fi
}

# ==============================================================================
# STATUS
# ==============================================================================

case_status() {
    cd_compose
    SERVER_IP=\$(curl -s --max-time 3 ifconfig.me 2>/dev/null || echo "unknown")

    echo -e "\${CYAN}=== VELO Status ===\${NC}"
    echo ""
    echo "Server: \$SERVER_IP"
    echo "Uptime: \$(uptime -p 2>/dev/null || uptime)"
    echo "Memory: \$(free -h | awk '/Mem:/ {print \$3 "/" \$2}')"
    echo "Disk:   \$(df -h / | tail -1 | awk '{print \$3 "/" \$2 " (" \$5 " used)"}')"
    echo ""

    echo -e "\${CYAN}=== Docker Containers ===\${NC}"
    docker compose ps
    echo ""

    echo -e "\${CYAN}=== Health (/health) ===\${NC}"
    HEALTH=\$(curl -s --max-time 5 "http://127.0.0.1:\${APP_PORT}/health" 2>/dev/null)
    if [ -n "\$HEALTH" ]; then
        echo "\$HEALTH" | python3 -m json.tool 2>/dev/null || echo "\$HEALTH"
    else
        echo -e "\${RED}✗ App not responding on localhost\${NC}"
    fi
    echo ""

    echo -e "\${CYAN}=== Readiness (/ready) ===\${NC}"
    READY_CODE=\$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "http://127.0.0.1:\${APP_PORT}/ready" 2>/dev/null || echo "000")
    if [ "\$READY_CODE" = "200" ]; then
        echo -e "\${GREEN}✓ /ready -> 200 (all dependencies healthy)\${NC}"
    elif [ "\$READY_CODE" = "503" ]; then
        echo -e "\${YELLOW}⚠ /ready -> 503 (degraded -- see /health above)\${NC}"
    else
        echo -e "\${RED}✗ /ready -> \$READY_CODE (unexpected)\${NC}"
    fi
    echo ""

    echo -e "\${CYAN}=== External Access ===\${NC}"
    if curl -sf --max-time 5 "https://\${DOMAIN_API}/health" > /dev/null 2>&1; then
        echo -e "\${GREEN}✓ https://\${DOMAIN_API}/health OK\${NC}"
    else
        echo -e "\${RED}✗ https://\${DOMAIN_API}/health unreachable\${NC}"
    fi
    if curl -sf --max-time 5 "https://\${DOMAIN_FRONTEND}" > /dev/null 2>&1; then
        echo -e "\${GREEN}✓ https://\${DOMAIN_FRONTEND} OK\${NC}"
    else
        echo -e "\${YELLOW}⚠ https://\${DOMAIN_FRONTEND} not reachable (frontend may be down)\${NC}"
    fi
}

# ==============================================================================
# LOGS
# ==============================================================================

case_logs() {
    cd_compose
    case "\${1:-app}" in
        app)         docker compose logs -f --tail=100 app ;;
        db|postgres) docker compose logs -f --tail=100 postgres ;;
        redis)       docker compose logs -f --tail=100 redis ;;
        frontend)    docker compose logs -f --tail=100 frontend 2>/dev/null || echo "Frontend not running" ;;
        all|"")      docker compose logs -f --tail=100 ;;
        *)           echo "Usage: velo logs [app|db|redis|frontend|all]" ;;
    esac
}

# ==============================================================================
# TEST
# ==============================================================================
#
# Backend tests run inside the app container via pytest.
# Frontend tests run inside the builder stage of the frontend Dockerfile --
# this is the same vitest run that happens during `velo update`, executed
# here on demand without rebuilding the whole image.
# ==============================================================================

run_frontend_tests() {
    cd_compose
    source_vite_env
    docker compose build --target builder frontend 2>&1 | tail -20
}

case_test() {
    cd_compose
    FAILED=0
    case "\${1:-all}" in
        backend|"")
            echo "=== Backend Tests ==="
            if ! docker compose exec -T app python -m pytest tests/ -v --tb=short; then
                FAILED=1
            fi
            ;;
        frontend)
            echo "=== Frontend Tests (inside builder stage) ==="
            if ! run_frontend_tests; then
                FAILED=1
            fi
            ;;
        all)
            echo "=== Backend Tests ==="
            if ! docker compose exec -T app python -m pytest tests/ -v --tb=short; then
                FAILED=1
            fi
            echo ""
            echo "=== Frontend Tests ==="
            if ! run_frontend_tests; then
                FAILED=1
            fi
            ;;
        *)
            echo "Usage: velo test [backend|frontend|all]"
            exit 1
            ;;
    esac
    echo ""
    if [ \$FAILED -ne 0 ]; then
        echo -e "\${RED}✗ Tests failed\${NC}"
        exit 1
    else
        echo -e "\${GREEN}✓ All tests passed\${NC}"
    fi
}

# ==============================================================================
# LINT
# ==============================================================================

case_lint() {
    cd_compose
    echo "=== Ruff (backend) ==="
    docker compose exec -T app python -m ruff check app/ tests/
    echo ""
    echo "=== Mypy (backend) ==="
    docker compose exec -T app python -m mypy app/ || true
    echo ""
    echo "=== ESLint (frontend) ==="
    docker compose exec -T frontend sh -c "cd /app 2>/dev/null && npx eslint . || true" 2>/dev/null \
        || echo -e "\${YELLOW}⚠ Frontend lint not available (container runtime stage has no source)\${NC}"
}

# ==============================================================================
# UPDATE
# ==============================================================================
#
# Standard flow:
#   1. Show current commit + branch.
#   2. If uncommitted changes -- prompt to discard.
#   3. git fetch + git diff origin/BRANCH. If no diff -> "Already up to date",
#      exit. To bypass, pass --force.
#   4. git pull.
#   5. Rebuild backend image.
#   6. Down stack, up backend+postgres+redis (frontend deferred).
#   7. Wait for /health (process alive).
#   8. Run migrations.
#   9. Regenerate generated.ts from live OpenAPI.
#   10. If generated.ts changed -- bot-commit + push (single rebase retry).
#   11. Run backend pytest (informational -- doesn't abort the rest).
#   12. Rebuild frontend image (with fresh types).
#   13. Up frontend.
#   14. Final /ready check.
#
# --force:
#   Skips the "Already up to date" early exit. Useful when the working tree
#   was modified outside the normal pull flow (e.g. you manually checked out
#   a different branch) and you want to rebuild and re-deploy regardless.
# ==============================================================================

case_update() {
    cd_compose

    FORCE=0
    if [ "\${1:-}" = "--force" ]; then
        FORCE=1
    fi

    echo "=== Updating VELO ==="
    echo ""

    # Save current state.
    CURRENT_COMMIT=\$(git rev-parse --short HEAD)
    BRANCH=\$(git branch --show-current)
    echo "Current: \$CURRENT_COMMIT (\$BRANCH)"

    # Check uncommitted changes. We use git status --porcelain rather than
    # git diff-index --quiet because the latter false-positives on stat
    # metadata drift (chmod, touch, FS restore) even with identical content.
    if [ -n "\$(git status --porcelain)" ]; then
        echo -e "\${YELLOW}⚠ Uncommitted changes detected:\${NC}"
        git status --short
        echo ""
        read -rp "Discard local changes and update? (y/n): " -n 1 < /dev/tty
        echo
        if [[ ! \$REPLY =~ ^[Yy]\$ ]]; then
            echo "Update cancelled"
            return 0
        fi
        git checkout -- .
    fi

    # Fetch and compare. The deploy key alias picks up the right key.
    git fetch origin
    if git diff --quiet HEAD "origin/\$BRANCH" 2>/dev/null && [ "\$FORCE" = "0" ]; then
        echo -e "\${GREEN}✓ Already up to date\${NC} (use --force to rebuild anyway)"
        return 0
    fi

    if [ "\$FORCE" = "1" ] && git diff --quiet HEAD "origin/\$BRANCH" 2>/dev/null; then
        echo "Force update: rebuilding without new commits"
    else
        echo "Pulling updates..."
        if ! git pull origin "\$BRANCH"; then
            echo -e "\${RED}✗ git pull failed.\${NC}"
            echo "  Inspect: git -C \$COMPOSE_DIR status"
            return 1
        fi
        NEW_COMMIT=\$(git rev-parse --short HEAD)
        echo "Updated: \$CURRENT_COMMIT -> \$NEW_COMMIT"
    fi
    echo ""

    # Rebuild backend image.
    echo "Rebuilding backend image..."
    source_vite_env
    docker compose build app

    # Restart stack: down everything, up infra+backend first (frontend
    # waits for fresh generated.ts).
    echo "Restarting backend + infra..."
    docker compose down
    docker compose up -d app postgres redis

    # Wait for process to come up.
    echo "Waiting for backend..."
    for i in \$(seq 1 18); do
        if curl -sf "http://127.0.0.1:\${APP_PORT}/health" > /dev/null 2>&1; then
            echo -e "\${GREEN}✓ Backend up\${NC}"
            break
        fi
        if [ "\$i" = "18" ]; then
            echo -e "\${RED}✗ Backend did not respond within 90s\${NC}"
            docker compose logs --tail=30 app
            return 1
        fi
        echo -n "."
        sleep 5
    done
    echo ""

    # Migrations.
    echo "Running database migrations..."
    docker compose exec -T app python -m alembic upgrade head || {
        echo -e "\${RED}✗ Migration failed\${NC}"
        return 1
    }
    echo -e "\${GREEN}✓ Migrations applied\${NC}"

    # Regenerate types BEFORE pytest, so any tests that check generated
    # schema integrity see the current file.
    echo ""
    echo "Regenerating frontend types from live OpenAPI..."
    if ! curl -sf "http://127.0.0.1:\${APP_PORT}/openapi.json" -o /tmp/openapi.json; then
        echo -e "\${RED}✗ Cannot fetch /openapi.json from backend\${NC}"
        return 1
    fi
    python3 "\$COMPOSE_DIR/backend/scripts/generate_ts_types.py" \\
        /tmp/openapi.json \\
        "\$COMPOSE_DIR/frontend/src/api/generated.ts" || {
        echo -e "\${RED}✗ generate_ts_types.py failed\${NC}"
        rm -f /tmp/openapi.json
        return 1
    }
    rm -f /tmp/openapi.json

    # Bot-commit if generated.ts drifted.
    if [ -n "\$(git status --porcelain frontend/src/api/generated.ts)" ]; then
        echo "Schema drift detected -- committing regenerated generated.ts"
        git add frontend/src/api/generated.ts
        git -c user.name="\$BOT_NAME" -c user.email="\$BOT_EMAIL" commit -m \\
"chore(types): regenerate generated.ts

Triggered by velo update on commit \$(git rev-parse --short HEAD~)."

        PUSH_OK=0
        for attempt in 1 2; do
            if git push origin "\$BRANCH"; then
                PUSH_OK=1; break
            fi
            if [ "\$attempt" = "1" ]; then
                echo "Push failed (likely a parallel push). Rebasing and retrying..."
                git pull --rebase origin "\$BRANCH" || break
            fi
        done
        if [ "\$PUSH_OK" = "0" ]; then
            echo -e "\${RED}✗ Failed to push regenerated types\${NC}"
            echo "  Bot commit exists locally on \$COMPOSE_DIR but is not on origin."
            return 1
        fi
        echo -e "\${GREEN}✓ Bot pushed regenerated types\${NC}"
    else
        echo -e "\${GREEN}✓ Types are in sync\${NC}"
    fi

    # Backend tests -- informational only. We don't abort the rest of the
    # pipeline; the dev site stays usable so you can debug. We propagate
    # the failure as the script exit code at the end.
    echo ""
    echo "Running backend tests..."
    pytest_status=0
    docker compose exec -T app python -m pytest tests/ -v --tb=short \\
        || pytest_status=\$?
    if [ \$pytest_status -eq 0 ]; then
        echo -e "\${GREEN}✓ All backend tests passed\${NC}"
    else
        echo -e "\${RED}✗ Backend tests failed -- continuing with frontend build\${NC}"
    fi

    # Rebuild frontend with fresh types.
    echo ""
    echo "Building frontend (vue-tsc + vite + vitest run inside)..."
    docker compose build frontend || {
        echo -e "\${RED}✗ Frontend build failed -- backend is still running\${NC}"
        echo "  See output above for the actual error."
        return 1
    }
    docker compose up -d frontend

    # Final readiness check.
    echo ""
    echo "Waiting for /ready..."
    for i in \$(seq 1 12); do
        if curl -sf "http://127.0.0.1:\${APP_PORT}/ready" > /dev/null 2>&1; then
            echo -e "\${GREEN}✓ /ready -> 200\${NC}"
            break
        fi
        if [ "\$i" = "12" ]; then
            echo -e "\${YELLOW}⚠ /ready did not return 200 within 60s\${NC}"
        fi
        echo -n "."
        sleep 5
    done

    echo ""
    echo -e "\${GREEN}✓ Update complete\${NC}"

    # Propagate pytest exit code.
    if [ \$pytest_status -ne 0 ]; then
        return 1
    fi
}

# ==============================================================================
# GEN-TYPES
# ==============================================================================
#
# Manual regeneration of frontend/src/api/generated.ts from the live backend
# OpenAPI. Does NOT commit or push -- only writes the file. Use this when
# iterating on a new Pydantic schema and you want fresh types in your IDE.
# `velo update` handles the commit/push cycle.
# ==============================================================================

case_gen_types() {
    cd_compose
    if ! curl -sf "http://127.0.0.1:\${APP_PORT}/openapi.json" -o /tmp/openapi.json; then
        echo -e "\${RED}✗ Cannot fetch /openapi.json from backend\${NC}"
        echo "  Is the app container running?  velo status"
        return 1
    fi
    python3 "\$COMPOSE_DIR/backend/scripts/generate_ts_types.py" \\
        /tmp/openapi.json \\
        "\$COMPOSE_DIR/frontend/src/api/generated.ts" || {
        rm -f /tmp/openapi.json
        echo -e "\${RED}✗ generate_ts_types.py failed\${NC}"
        return 1
    }
    rm -f /tmp/openapi.json
    if [ -n "\$(git status --porcelain frontend/src/api/generated.ts)" ]; then
        echo -e "\${YELLOW}⚠ generated.ts changed -- not committed\${NC}"
        echo "  Run 'velo update' to commit and push, or commit by hand."
    else
        echo -e "\${GREEN}✓ generated.ts is already in sync\${NC}"
    fi
}

# ==============================================================================
# RESTART
# ==============================================================================

case_restart() {
    cd_compose
    SERVICE="\${1:-}"
    if [ -n "\$SERVICE" ]; then
        echo "Restarting \$SERVICE..."
        docker compose restart "\$SERVICE"
    else
        echo "Restarting all services..."
        docker compose restart
    fi
    echo -e "\${GREEN}✓ Done\${NC}"
}

# ==============================================================================
# BACKUP
# ==============================================================================
#
# Test-server backup: pg_dump + backend/.env into a tarball with 7-day rotation.
# This is convenience, not safety -- the test server is disposable. The cron
# at 4 AM exists so a manual command isn't required during routine dev.
# ==============================================================================

case_backup() {
    cd_compose
    TIMESTAMP=\$(date +%Y%m%d_%H%M%S)
    BACKUP_DIR="\$INSTALL_BASE/backups"
    BACKUP_FILE="\$BACKUP_DIR/velo_backup_\${TIMESTAMP}.tar.gz"
    DB_DUMP_FILE="/tmp/velo_db_\${TIMESTAMP}.sql"
    mkdir -p "\$BACKUP_DIR"

    echo "Creating backup..."
    echo "  Dumping PostgreSQL..."
    docker compose exec -T postgres pg_dump -U velo velo > "\$DB_DUMP_FILE"

    echo "  Creating archive..."
    tar -czf "\$BACKUP_FILE" \\
        -C /tmp "velo_db_\${TIMESTAMP}.sql" \\
        -C "\$COMPOSE_DIR/backend" ".env"
    rm -f "\$DB_DUMP_FILE"

    # Rotate -- keep last 7 days.
    find "\$BACKUP_DIR" -name "velo_backup_*.tar.gz" -mtime +7 -delete

    echo -e "\${GREEN}✓ Backup: \$BACKUP_FILE\${NC}"
    ls -lh "\$BACKUP_FILE"
}

# ==============================================================================
# DATABASE
# ==============================================================================

case_db() {
    cd_compose
    case "\${1:-connect}" in
        connect)
            docker compose exec postgres psql -U velo -d velo
            ;;
        dump)
            TIMESTAMP=\$(date +%Y%m%d_%H%M%S)
            DUMP_FILE="\$INSTALL_BASE/backups/velo_db_\${TIMESTAMP}.sql"
            mkdir -p "\$INSTALL_BASE/backups"
            docker compose exec -T postgres pg_dump -U velo velo > "\$DUMP_FILE"
            echo -e "\${GREEN}✓ Dump: \$DUMP_FILE\${NC}"
            ;;
        restore)
            if [ -z "\${2:-}" ]; then
                echo "Usage: velo db restore <file>"
                exit 1
            fi
            if [ ! -f "\$2" ]; then
                echo -e "\${RED}File not found: \$2\${NC}"
                exit 1
            fi
            echo -e "\${YELLOW}⚠ This will overwrite the current database!\${NC}"
            read -rp "Are you sure? (y/n): " -n 1 < /dev/tty
            echo
            if [[ \$REPLY =~ ^[Yy]\$ ]]; then
                echo "Restoring database..."
                cat "\$2" | docker compose exec -T postgres psql -U velo velo
                echo -e "\${GREEN}✓ Database restored\${NC}"
            fi
            ;;
        migrate)
            echo "Running Alembic migrations..."
            docker compose exec -T app python -m alembic upgrade head
            echo -e "\${GREEN}✓ Migrations complete\${NC}"
            ;;
        *)
            echo "Database commands:"
            echo "  velo db connect          -- Open psql session"
            echo "  velo db dump             -- Create SQL dump"
            echo "  velo db restore <file>   -- Restore from dump"
            echo "  velo db migrate          -- Run Alembic migrations"
            ;;
    esac
}

# ==============================================================================
# SEED
# ==============================================================================
#
# scripts/seed.py is interactive -- it asks for Telegram IDs of test masters,
# users, and admins. That's why seeding is NEVER triggered automatically by
# velo update; only the operator runs `velo seed` when they want test data.
# ==============================================================================

case_seed() {
    cd_compose
    SEED_ARGS=""
    if [ "\${1:-}" = "--reset" ]; then
        SEED_ARGS="--reset"
    fi
    docker compose exec app python scripts/seed.py \$SEED_ARGS
}

# ==============================================================================
# SSL
# ==============================================================================

case_ssl() {
    case "\${1:-status}" in
        renew)
            echo "Renewing SSL certificates..."
            certbot renew --quiet --post-hook "systemctl reload nginx"
            echo -e "\${GREEN}✓ SSL renewed\${NC}"
            ;;
        status)
            echo "SSL certificate status:"
            certbot certificates 2>/dev/null || echo "No certificates found"
            ;;
        *)
            echo "SSL commands:"
            echo "  velo ssl renew    -- Renew SSL certificates"
            echo "  velo ssl status   -- Show certificate info"
            ;;
    esac
}

# ==============================================================================
# NGINX
# ==============================================================================

case_nginx() {
    case "\${1:-reload}" in
        reload)
            nginx -t && systemctl reload nginx
            echo -e "\${GREEN}✓ Nginx reloaded\${NC}"
            ;;
        status)
            systemctl status nginx --no-pager -l
            ;;
        *)
            echo "Nginx commands:"
            echo "  velo nginx reload   -- Test config and reload Nginx"
            echo "  velo nginx status   -- Show Nginx status"
            ;;
    esac
}

# ==============================================================================
# VERSION
# ==============================================================================

case_version() {
    cd_compose
    echo "=== VELO Version ==="
    echo ""
    echo "Git log (last 5 commits):"
    git log --oneline -5
    echo ""
    echo "Branch: \$(git branch --show-current)"
    echo "Commit: \$(git rev-parse HEAD)"
    echo ""
    echo "Runtime:"
    docker compose exec -T app python --version 2>/dev/null || true
    docker --version
    docker compose version
    echo ""
    echo "Images:"
    docker images --filter "reference=repo-*" --format "  {{.Repository}}:{{.Tag}}  {{.Size}}  {{.CreatedSince}}"
}

# ==============================================================================
# MAIN DISPATCH
# ==============================================================================

CMD="\${1:-help}"
shift 2>/dev/null || true

case "\$CMD" in
    status)         case_status ;;
    logs)           case_logs "\$@" ;;
    test)           case_test "\$@" ;;
    lint)           case_lint ;;
    update|deploy)  case_update "\$@" ;;
    gen-types)      case_gen_types ;;
    restart)        case_restart "\$@" ;;
    backup)         case_backup ;;
    db)             case_db "\$@" ;;
    seed)           case_seed "\$@" ;;
    ssl)            case_ssl "\$@" ;;
    nginx)          case_nginx "\$@" ;;
    version)        case_version ;;
    help|*)
        echo -e "\${CYAN}VELO Management Script\${NC}"
        echo ""
        echo "Usage: velo <command> [options]"
        echo ""
        echo "Monitoring:"
        echo "  status                                — Docker + /health + /ready + external access"
        echo "  logs [app|db|redis|frontend|all]      — View logs (default: app)"
        echo "  version                               — Git log + runtime versions"
        echo ""
        echo "Testing:"
        echo "  test [backend|frontend|all]           — Run tests (default: all)"
        echo "  lint                                  — Run ruff + mypy + eslint"
        echo ""
        echo "Deployment:"
        echo "  update [--force]                      — Pull, rebuild, migrate, regen-types, deploy"
        echo "                                          --force: rebuild without new commits"
        echo "  gen-types                             — Regenerate generated.ts (no commit)"
        echo "  restart [service]                     — Restart all or specific service"
        echo ""
        echo "Database:"
        echo "  db connect                            — Open psql session"
        echo "  db dump                               — Create SQL dump"
        echo "  db restore <file>                     — Restore from dump"
        echo "  db migrate                            — Run Alembic migrations"
        echo "  seed [--reset]                        — Seed test data (interactive)"
        echo ""
        echo "Maintenance:"
        echo "  backup                                — Backup DB + .env (7-day rotation)"
        echo "  ssl renew                             — Renew SSL certificates"
        echo "  ssl status                            — Show certificate info"
        echo "  nginx reload                          — Test config and reload Nginx"
        ;;
esac
MANAGE_EOF

chmod +x "$MANAGE_SCRIPT"
ln -sf "$MANAGE_SCRIPT" /usr/local/bin/velo
success "Management script: /usr/local/bin/velo"

# ==============================================================================
# BACKUP CRON
# ==============================================================================

section "Backup Cron"

(crontab -l 2>/dev/null; \
 echo "0 4 * * * /usr/local/bin/velo backup >> /var/log/velo-backup.log 2>&1") \
    | sort -u | crontab -
success "Backup cron: 4 AM daily, 7-day rotation"

# ==============================================================================
# DONE
# ==============================================================================

echo ""
echo -e "${GREEN}${BOLD}"
echo "╔══════════════════════════════════════════════════╗"
echo "║           VELO Installation Complete!            ║"
echo "╚══════════════════════════════════════════════════╝"
echo -e "${NC}"
echo -e "API:      ${CYAN}https://${DOMAIN_API}/health${NC}"
echo -e "Frontend: ${CYAN}https://${DOMAIN_FRONTEND}${NC}"
echo ""
echo -e "Management: ${CYAN}velo status | velo logs | velo update${NC}"
echo ""
echo -e "${YELLOW}NEXT STEPS:${NC}"
echo "1. Run: velo seed     -- (optional) populate test data"
echo "2. Run: velo status   -- verify everything is green"
echo "3. Open: https://${DOMAIN_FRONTEND}"
echo ""
