// =============================================================================
// VELO Frontend -- MyBookingsView Screen Tests (T8, ПРОМТ №431)
// =============================================================================
//
// First screen test in the repo. Generated by probekit-screen-test; the idiom
// is copied from the existing 23 test files, not invented -- createApp +
// happy-dom (no @vue/test-utils, per MethodTaxonomyPicker.test.ts:19-20), real
// Pinia + mocked API wrapper (per stores/bookings.test.ts:21-32), vue-router
// mocked rather than built (guards.test.ts never builds one either).
//
// PATTERN A (store-backed): state lives in useBookingsStore, so the seam is
// @/api/bookings -- the wrapper the store imports. The store is REAL; only the
// network boundary is faked.
//
// The ONE new thing vs the existing suite: the mount needs Pinia inside it
// (app.use(pinia)), which no prior test needed -- leaf components took no
// stores. The same pinia instance goes to setActivePinia AND app.use; two
// instances would mean the test mutates one store while the screen renders
// another, and every assertion would pass while proving nothing.
//
// TIME IS PINNED (vi.setSystemTime). The screen reads Date.now()/new Date() in
// upcomingRank/isToday/isTomorrow/badgeFor, so «Сегодня»/«Завтра» and the sort
// order are wall-clock dependent; fixtures below are literals relative to the
// frozen instant, and practice.timezone is 'UTC' so Intl's calendar-date
// comparison can't drift across the runner's local zone.
// =============================================================================

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { createApp, nextTick, type App } from 'vue'
import { setActivePinia, createPinia, type Pinia } from 'pinia'
import MyBookingsView from '@/views/user/MyBookingsView.vue'
import * as bookingsApi from '@/api/bookings'
// The REAL store, read where the assertion is about which error ref a failure
// landed in -- the distinction the №442 root fix introduced.
import { useBookingsStore } from '@/stores/bookings'
import { useAuthStore } from '@/stores/auth'
import type { BookingWithPracticeResponse, UserResponse } from '@/api/types'

vi.mock('@/api/bookings')

const push = vi.fn()
const back = vi.fn()
vi.mock('vue-router', () => ({
  useRouter: () => ({ push, back }),
}))

// The store pulls in useDiaryStore() lazily inside cancelBooking; mocked
// wholesale so nothing from that store's own network path evaluates here.
vi.mock('@/stores/diary', () => ({
  useDiaryStore: () => ({ refreshFeed: vi.fn() }),
}))

// A failed «Показать ещё» toasts (.vue:onLoadMore) -- the toast IS the entire
// user-facing half of that path, so it has to be a real assertion seam.
const toastError = vi.fn()
vi.mock('@/composables/useToast', () => ({
  useToast: () => ({ error: toastError, success: vi.fn(), info: vi.fn() }),
}))

const NOW = new Date('2026-07-20T12:00:00Z')

function booking(
  id: string,
  overrides: Partial<BookingWithPracticeResponse> = {},
  practice: Partial<BookingWithPracticeResponse['practice']> = {},
): BookingWithPracticeResponse {
  return {
    id,
    practice_id: `practice_${id}`,
    user_id: 'user_1',
    status: 'confirmed',
    purchase_id: null,
    cancelled_at: null,
    cancellation_reason: null,
    joined_at: null,
    left_at: null,
    checkin_skipped: false,
    created_at: '2026-07-01T00:00:00Z',
    updated_at: null,
    has_feedback: false,
    has_checkin: false,
    ...overrides,
    practice: {
      id: `practice_${id}`,
      title: `Practice ${id}`,
      practice_type: 'live',
      status: 'scheduled',
      scheduled_at: '2026-07-25T10:00:00Z',
      duration_minutes: 60,
      timezone: 'UTC',
      master_id: 'master_1',
      master_name: 'Мастер',
      direction: null,
      is_free: true,
      price_cents: 0,
      currency: 'RUB',
      zoom_link: null,
      ...practice,
    } as BookingWithPracticeResponse['practice'],
  }
}

function page(items: BookingWithPracticeResponse[], total = items.length) {
  return { items, total, limit: 20, offset: 0 }
}

// SW3: the viewer's profile timezone, distinct from every fixture's own
// practice.timezone (default 'UTC') -- used to prove isToday/isTomorrow/
// badgeFor read the VIEWER's tz, not the practice's own.
const VIEWER_TZ = 'Europe/Moscow' // UTC+3

function user(overrides: Partial<UserResponse> = {}): UserResponse {
  return {
    id: 'user_1',
    telegram_id: 1,
    role: 'user',
    first_name: 'Аня',
    last_name: null,
    avatar_url: null,
    timezone: VIEWER_TZ,
    language: 'ru',
    is_active: true,
    balance_cents: 0,
    created_at: '2026-01-01T00:00:00Z',
    last_login_at: null,
    onboarding_completed: true,
    master_onboarding_completed: false,
    phone: null,
    bio: null,
    email: null,
    notifications: {} as UserResponse['notifications'],
    master_notifications: null,
    role_switch: null,
    ...overrides,
  }
}

let app: App | null = null
let host: HTMLElement | null = null
let pinia: Pinia

function mount(): HTMLElement {
  host = document.createElement('div')
  document.body.appendChild(host)
  app = createApp(MyBookingsView)
  app.use(pinia)
  app.mount(host)
  return host
}

// onMounted -> store.fetchMyBookings() -> pagination.refresh() -> awaited
// fetch + its continuation + the re-render. One tick is not enough
// (CalendarFilterModal.test.ts:71-74 flushes three for the same reason).
async function flush(): Promise<void> {
  await nextTick()
  await nextTick()
  await nextTick()
}

function text(): string {
  return host?.textContent ?? ''
}

beforeEach(() => {
  vi.setSystemTime(NOW)
  pinia = createPinia()
  setActivePinia(pinia)
  vi.mocked(bookingsApi.getMyBookings).mockReset().mockResolvedValue(page([]))
  useAuthStore().user = user()
  push.mockReset()
  back.mockReset()
})

afterEach(() => {
  app?.unmount()
  host?.remove()
  app = null
  host = null
  vi.useRealTimers()
  vi.clearAllMocks()
})

describe('MyBookingsView', () => {
  describe('state ladder', () => {
    it('initial load: shows the loader while the first page is in flight', async () => {
      // Never resolves -> store.loading stays true with an empty list, which is
      // exactly the v-if guard at MyBookingsView.vue:22.
      vi.mocked(bookingsApi.getMyBookings).mockReturnValue(
        new Promise(() => {}) as Promise<ReturnType<typeof page>>,
      )
      mount()
      await flush()

      expect(host?.querySelector('.bookings__loader')).not.toBeNull()
      expect(text()).not.toContain('Бронирований нет')
    })

    it('error: shows the error state and surfaces the REAL backend message', async () => {
      // usePagination.ts:68 assigns e.message verbatim, and the screen binds
      // :description="store.error" (MyBookingsView.vue:31) -- so the actual
      // message must reach the DOM, not a hardcoded fallback.
      vi.mocked(bookingsApi.getMyBookings).mockRejectedValue(new Error('Сервис недоступен'))
      mount()
      await flush()

      expect(text()).toContain('Ошибка загрузки')
      expect(text()).toContain('Сервис недоступен')
    })

    it('error retry: the button re-fetches through the store', async () => {
      vi.mocked(bookingsApi.getMyBookings).mockRejectedValue(new Error('Сервис недоступен'))
      mount()
      await flush()
      vi.mocked(bookingsApi.getMyBookings).mockClear()

      const retry = Array.from(host?.querySelectorAll('button') ?? []).find((b) =>
        b.textContent?.includes('Попробовать снова'),
      )
      expect(retry).toBeDefined()
      retry?.click()
      await flush()

      expect(bookingsApi.getMyBookings).toHaveBeenCalled()
    })

    it('empty: shows the empty state when the page is genuinely empty', async () => {
      mount()
      await flush()

      expect(text()).toContain('Бронирований нет')
      expect(host?.querySelector('.bookings__loader')).toBeNull()
    })

    it('content: renders what the store actually returned', async () => {
      vi.mocked(bookingsApi.getMyBookings).mockResolvedValue(
        page([booking('b1', {}, { title: 'Утренняя практика' })]),
      )
      mount()
      await flush()

      expect(text()).toContain('Утренняя практика')
      expect(text()).not.toContain('Бронирований нет')
    })

    it('a load-more failure keeps content visible AND tells the user (№442)', async () => {
      // Half of this was already true and half of it was the bug. The list
      // surviving is the guard at .vue:22,28 doing its job. But until №442 the
      // failure was NEVER surfaced: `store.error` appears nowhere outside that
      // guarded rung, so the tap did nothing and nothing said why -- the silent
      // variant the whole session has been chasing. The toast is the other half;
      // drop it and this test fails.
      vi.mocked(bookingsApi.getMyBookings).mockResolvedValue(
        page([booking('b1', {}, { title: 'Утренняя практика' })], 40),
      )
      mount()
      await flush()

      vi.mocked(bookingsApi.getMyBookings).mockRejectedValue(new Error('Сеть отвалилась'))
      const more = Array.from(host?.querySelectorAll('button') ?? []).find((b) =>
        b.textContent?.includes('Показать ещё'),
      )
      expect(more).toBeDefined()
      more?.click()
      await flush()

      expect(text()).toContain('Утренняя практика')
      expect(text()).not.toContain('Ошибка загрузки')
      expect(toastError).toHaveBeenCalledWith('Сеть отвалилась')
    })

    it('routes the load-more failure to loadMoreError, leaving the rung error null', async () => {
      // The root fix (usePagination): `error` = first page, `loadMoreError` =
      // later page. `error` staying null is what makes the surviving list
      // structural rather than a guard each screen has to remember.
      vi.mocked(bookingsApi.getMyBookings).mockResolvedValue(
        page([booking('b1', {}, { title: 'Утренняя практика' })], 40),
      )
      mount()
      await flush()

      vi.mocked(bookingsApi.getMyBookings).mockRejectedValue(new Error('Сеть отвалилась'))
      Array.from(host?.querySelectorAll('button') ?? [])
        .find((b) => b.textContent?.includes('Показать ещё'))
        ?.click()
      await flush()

      const store = useBookingsStore()
      expect(store.error).toBeNull()
      expect(store.loadMoreError).toBe('Сеть отвалилась')
    })

    it('an INITIAL-load failure still fills `error`, not loadMoreError', async () => {
      // The other side of the split: it must not become a blanket redirect that
      // silences the first page too. Without this, routing everything to
      // loadMoreError would pass every other test in this file.
      vi.mocked(bookingsApi.getMyBookings).mockRejectedValue(new Error('Сервис недоступен'))
      mount()
      await flush()

      const store = useBookingsStore()
      expect(store.error).toBe('Сервис недоступен')
      expect(store.loadMoreError).toBeNull()
      expect(text()).toContain('Сервис недоступен')
      expect(toastError).not.toHaveBeenCalled()
    })
  })

  describe('grouping and badges', () => {
    it('splits upcoming from past and badges each by its own rule', async () => {
      vi.mocked(bookingsApi.getMyBookings).mockResolvedValue(
        page([
          // ended 10 days ago, attended -> «Прошедшие» + «Завершена»
          booking('past1', { status: 'attended' }, { scheduled_at: '2026-07-10T10:00:00Z' }),
          // later today -> «Предстоящие» + «Сегодня»
          booking('today1', {}, { scheduled_at: '2026-07-20T18:00:00Z' }),
          // tomorrow -> «Предстоящие» + «Завтра»
          booking('tom1', {}, { scheduled_at: '2026-07-21T10:00:00Z' }),
        ]),
      )
      mount()
      await flush()

      expect(text()).toContain('Предстоящие')
      expect(text()).toContain('Прошедшие')
      expect(text()).toContain('Сегодня')
      expect(text()).toContain('Завтра')
      expect(text()).toContain('Завершена')
    })

    it('a confirmed booking whose practice already ended is past and carries NO upcoming badge', async () => {
      // MyBookingsView.vue:198-201: the backend keeps confirmed until finalize
      // (settlement grace window), so status alone would mis-file it as upcoming
      // and paint a misleading «Сегодня» on a practice that is over.
      vi.mocked(bookingsApi.getMyBookings).mockResolvedValue(
        page([
          booking(
            'ended',
            { status: 'confirmed' },
            { scheduled_at: '2026-07-20T09:00:00Z', duration_minutes: 60 },
          ),
        ]),
      )
      mount()
      await flush()

      expect(text()).toContain('Прошедшие')
      expect(text()).not.toContain('Предстоящие')
      expect(text()).not.toContain('Сегодня')
      expect(text()).not.toContain('В эфире')
    })

    it('a practice in progress is upcoming and badged «В эфире»', async () => {
      vi.mocked(bookingsApi.getMyBookings).mockResolvedValue(
        page([
          booking(
            'live',
            { status: 'confirmed' },
            { scheduled_at: '2026-07-20T11:30:00Z', duration_minutes: 60 },
          ),
        ]),
      )
      mount()
      await flush()

      expect(text()).toContain('Предстоящие')
      expect(text()).toContain('В эфире')
    })

    it('SW3: badge uses the VIEWER profile timezone, not the practice\'s own -- distinguishing fixture', async () => {
      // Same distinguishing instant/tz pair as CalendarView's SW2 test: 20:00
      // UTC on the 20th (after NOW=12:00Z, not live, not ended). In the
      // VIEWER's Moscow (UTC+3) that's 23:00 on the 20th -- same calendar day
      // as NOW there (15:00) -- so the correct badge is "Сегодня". In the
      // practice's OWN tz (Asia/Yekaterinburg, UTC+5, no DST) the same instant
      // is 01:00 on the 21st while NOW there is 17:00 on the 20th, so the OLD
      // buggy behaviour (reading b.practice.timezone) badges it "Завтра"
      // instead -- a genuinely different label, not a coincidental match.
      vi.mocked(bookingsApi.getMyBookings).mockResolvedValue(
        page([
          booking(
            'tzcheck',
            { status: 'confirmed' },
            { scheduled_at: '2026-07-20T20:00:00Z', duration_minutes: 60, timezone: 'Asia/Yekaterinburg' },
          ),
        ]),
      )
      mount()
      await flush()

      expect(text()).toContain('Сегодня')
      expect(text()).not.toContain('Завтра')
    })
  })

  describe('navigation', () => {
    it('tapping a booking opens the practice detail by practice_id, not booking id', async () => {
      // MyBookingsView.vue:213-218: the dedicated booking-detail screen is gone;
      // routing by the wrong id here would 404 at runtime.
      vi.mocked(bookingsApi.getMyBookings).mockResolvedValue(
        page([booking('b1', { practice_id: 'practice_42' }, { title: 'Утренняя практика' })]),
      )
      mount()
      await flush()

      const card = host?.querySelector<HTMLElement>('.bookings__list > *')
      expect(card).not.toBeNull()
      card?.click()
      await flush()

      expect(push).toHaveBeenCalledWith({
        name: 'practice-detail',
        params: { id: 'practice_42' },
      })
    })
  })
})
