// =============================================================================
// VELO Frontend -- TopupView Screen Tests (T8, ПРОМТ №432)
// =============================================================================
//
// The money-in door: this is the only screen in the app that mints a Stripe
// checkout session. Generated by probekit-screen-test; mount idiom copied from
// MyBookingsView.test.ts (createApp + happy-dom, real Pinia, mocked seams).
//
// PATTERN: hybrid, and the test mocks each half at ITS OWN layer --
//   - balance display is PATTERN A (store-backed): useBalanceStore is REAL, and
//     it is a thin derive over useAuthStore (stores/balance.ts:25) -- so the seam
//     is @/stores/auth, mocked wholesale behind getters per the guards.test.ts
//     trick (velo-idiom §5). Mocking @/stores/balance instead would delete the
//     very computation under test.
//   - submit is PATTERN B (local-ref): loading/customMode/customValue are refs
//     fed by a direct createTopup() call, so the seam is @/api/payments.
//
// NO state ladder here. This is a FORM screen: no loading/error/empty rungs to
// assert -- `loading` gates the button, not a loader, and there is no fetch to
// fail on mount. The ladder in SKILL.md Step 5 is list-screen shaped; see the
// report for that gap.
//
// window.location is REPLACED with a plain object per test. onTopup does a real
// `window.location.href = ...` assignment (TopupView.vue:186); left alone,
// happy-dom would try to navigate. The stand-in also lets us prove the C-1
// whitelist by reading back what the screen tried to navigate TO.
//
// import.meta.env.VITE_API_BASE_URL is EMPTY in .env (.env:15), so the
// `|| 'https://api.talentir.info'` fallback (TopupView.vue:106) is what is
// actually live. That `||` is load-bearing: an empty-string prefix would make
// `url.startsWith(prefix)` true for EVERY url and silently void the whitelist.
// The hostile-url test below is what would catch that regression.
//
// No time pinning needed -- this screen reads no clock.
// =============================================================================

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { createApp, nextTick, type App } from 'vue'
import { setActivePinia, createPinia, type Pinia } from 'pinia'
import TopupView from '@/views/user/TopupView.vue'
import * as paymentsApi from '@/api/payments'
import { ApiResponseError } from '@/api/client'
import type { TopupResponse } from '@/api/types'

// importOriginal + spread keeps ApiResponseError REAL, so the rejection test
// below asserts against the real class the screen does `instanceof` on
// (velo-idiom §4; payments.test.ts:18-29 mocks the client seam the same way).
vi.mock('@/api/payments', async (importOriginal) => {
  const actual = await importOriginal<typeof import('@/api/payments')>()
  return { ...actual, createTopup: vi.fn() }
})

const toastError = vi.fn()
const toastSuccess = vi.fn()
vi.mock('@/composables/useToast', () => ({
  useToast: () => ({ error: toastError, success: toastSuccess, info: vi.fn() }),
}))

// Dependency store, not under test -- mutable module-scope state behind getters
// so a test changes the balance instead of re-mocking (velo-idiom §5).
const authState: { user: { balance_cents: number } | null } = { user: null }
const fetchMe = vi.fn()
vi.mock('@/stores/auth', () => ({
  useAuthStore: () => ({
    get user() {
      return authState.user
    },
    fetchMe,
  }),
}))

// Full TopupResponse fixtures -- the screen only reads checkout_url, but the
// mock must satisfy the real contract or vue-tsc rejects the cast.
function topup(checkout_url: string): TopupResponse {
  return { payment_id: 'pay_1', checkout_url, amount_cents: 1000, currency: 'EUR' }
}

let app: App | null = null
let host: HTMLElement | null = null
let pinia: Pinia
let location: { href: string }

const realLocation = window.location

function mount(): HTMLElement {
  host = document.createElement('div')
  document.body.appendChild(host)
  app = createApp(TopupView)
  app.use(pinia)
  app.mount(host)
  return host
}

// onMounted -> balanceStore.refresh() -> awaited fetchMe + its continuation +
// the re-render (velo-idiom §3).
async function flush(): Promise<void> {
  await nextTick()
  await nextTick()
  await nextTick()
}

function text(): string {
  return host?.textContent ?? ''
}

function presets(): HTMLButtonElement[] {
  return Array.from(host?.querySelectorAll<HTMLButtonElement>('.topup__preset') ?? [])
}

function submitBtn(): HTMLButtonElement | undefined {
  return Array.from(host?.querySelectorAll('button') ?? []).find((b) =>
    b.textContent?.includes('Пополнить'),
  ) as HTMLButtonElement | undefined
}

function toggleCustom(): void {
  host?.querySelector<HTMLElement>('.topup__custom-toggle')?.click()
}

function typeCustom(value: string): void {
  const input = host?.querySelector<HTMLInputElement>('.topup__custom input')
  if (!input) throw new Error('custom input is not rendered -- call toggleCustom() first')
  input.value = value
  input.dispatchEvent(new Event('input'))
}

beforeEach(() => {
  pinia = createPinia()
  setActivePinia(pinia)
  authState.user = { balance_cents: 0 }
  fetchMe.mockReset().mockResolvedValue(undefined)
  vi.mocked(paymentsApi.createTopup).mockReset()
  toastError.mockReset()
  toastSuccess.mockReset()

  location = { href: '' }
  Object.defineProperty(window, 'location', {
    configurable: true,
    writable: true,
    value: location,
  })
})

afterEach(() => {
  app?.unmount()
  host?.remove()
  app = null
  host = null
  Object.defineProperty(window, 'location', {
    configurable: true,
    writable: true,
    value: realLocation,
  })
  vi.clearAllMocks()
})

describe('TopupView', () => {
  describe('balance', () => {
    it('renders the balance the auth store actually holds, through the real balance store', async () => {
      authState.user = { balance_cents: 1500 }
      mount()
      await flush()

      expect(text()).toContain('15,00')
    })

    it('a zero balance renders as money, not as «Бесплатно»', async () => {
      // stores/balance.ts:34-36 passes allowZero=true precisely for this;
      // formatMoney's default would print «Бесплатно» on a 0 balance
      // (utils/format.ts:33), which on a topup screen is nonsense.
      authState.user = { balance_cents: 0 }
      mount()
      await flush()

      expect(text()).toContain('0,00')
      expect(text()).not.toContain('Бесплатно')
    })

    it('refreshes the balance from the API on mount', async () => {
      // The user arrives here straight from a payment; a stale cached balance
      // is the whole reason for the onMounted refresh (TopupView.vue:199-201).
      mount()
      await flush()

      expect(fetchMe).toHaveBeenCalledTimes(1)
    })
  })

  describe('amount selection', () => {
    it('offers exactly the four preset amounts, formatted as EUR', async () => {
      mount()
      await flush()

      const labels = presets().map((b) => b.textContent?.trim())
      expect(labels).toHaveLength(4)
      expect(labels.join('|')).toContain('5,00')
      expect(labels.join('|')).toContain('10,00')
      expect(labels.join('|')).toContain('20,00')
      expect(labels.join('|')).toContain('50,00')
    })

    it('defaults to EUR 10 and says so on the button', async () => {
      mount()
      await flush()

      expect(submitBtn()?.textContent).toContain('10,00')
      expect(presets()[1]?.className).toContain('topup__preset--active')
    })

    it('picking a preset submits THAT amount in cents', async () => {
      vi.mocked(paymentsApi.createTopup).mockResolvedValue(topup('https://checkout.stripe.com/c/pay/abc'))
      mount()
      await flush()

      presets()[3]?.click() // EUR 50
      await flush()
      submitBtn()?.click()
      await flush()

      expect(paymentsApi.createTopup).toHaveBeenCalledWith(5000)
    })

    it('picking a preset clears a previously typed custom amount', async () => {
      // selectPreset() resets customMode AND customValue (TopupView.vue:146-150).
      // Leaving the stale custom value behind would let effectiveCents flip back
      // to it if custom mode were re-entered -- charging an amount the user is no
      // longer looking at.
      vi.mocked(paymentsApi.createTopup).mockResolvedValue(topup('https://checkout.stripe.com/c/pay/abc'))
      mount()
      await flush()

      toggleCustom()
      await flush()
      typeCustom('300')
      await flush()
      expect(submitBtn()?.textContent).toContain('300,00')

      presets()[0]?.click() // EUR 5
      await flush()

      expect(submitBtn()?.textContent).toContain('5,00')
      expect(host?.querySelector('.topup__custom input')).toBeNull()
      submitBtn()?.click()
      await flush()
      expect(paymentsApi.createTopup).toHaveBeenCalledWith(500)
    })
  })

  describe('custom amount validation', () => {
    it('converts the typed euro string to cents WITHOUT float math', async () => {
      // FP-03 (TopupView.vue:117-119): parseFloat('0.575') * 100 rounds to 57,
      // not 58. eurStringToCents parses the parts as integers instead. '15.99'
      // must reach the API as exactly 1599 -- a cent off is a real charge error.
      vi.mocked(paymentsApi.createTopup).mockResolvedValue(topup('https://checkout.stripe.com/c/pay/abc'))
      mount()
      await flush()

      toggleCustom()
      await flush()
      typeCustom('15.99')
      await flush()
      submitBtn()?.click()
      await flush()

      expect(paymentsApi.createTopup).toHaveBeenCalledWith(1599)
    })

    it('rejects below the EUR 1 minimum and blocks submit', async () => {
      mount()
      await flush()
      toggleCustom()
      await flush()
      typeCustom('0.50')
      await flush()

      expect(text()).toContain('Минимальная сумма — €1')
      expect(submitBtn()?.disabled).toBe(true)
    })

    it('rejects above the EUR 500 maximum and blocks submit', async () => {
      mount()
      await flush()
      toggleCustom()
      await flush()
      typeCustom('501')
      await flush()

      expect(text()).toContain('Максимальная сумма — €500')
      expect(submitBtn()?.disabled).toBe(true)
    })

    it('accepts the exact boundaries (1 and 500) -- they are IN range, not out', async () => {
      // MIN_CENTS/MAX_CENTS are compared with >= and <= (TopupView.vue:131-137);
      // an off-by-one to > / < would reject the two amounts most likely to be typed.
      mount()
      await flush()
      toggleCustom()
      await flush()

      typeCustom('1')
      await flush()
      expect(text()).not.toContain('Минимальная сумма')
      expect(submitBtn()?.disabled).toBe(false)

      typeCustom('500')
      await flush()
      expect(text()).not.toContain('Максимальная сумма')
      expect(submitBtn()?.disabled).toBe(false)
    })

    it('an empty custom field shows no error but still blocks submit', async () => {
      // validationError bails early on empty (TopupView.vue:125) so the user is
      // not scolded before typing -- but canSubmit must still be false, or the
      // button would fire a 0-cent topup.
      mount()
      await flush()
      toggleCustom()
      await flush()

      expect(text()).not.toContain('Минимальная сумма')
      expect(submitBtn()?.disabled).toBe(true)
    })

    it('a negative amount cannot be submitted', async () => {
      // The STATE guard holds: onCustomInput wipes customValue (TopupView.vue:158-162),
      // so effectiveCents is 0, canSubmit is false, and no negative topup can leave
      // the screen. This is the assertion that matters for money.
      mount()
      await flush()
      toggleCustom()
      await flush()
      typeCustom('-5')
      await flush()

      expect(submitBtn()?.disabled).toBe(true)
      expect(submitBtn()?.textContent).not.toContain('-5')
      submitBtn()?.click()
      await flush()
      expect(paymentsApi.createTopup).not.toHaveBeenCalled()
    })

    it('the wiped negative is gone from the FIELD too, not just from the state', async () => {
      // REGRESSION GUARD (T8, find from ПРОМТ №432, fixed in №434).
      // TopupView.vue:158-162 says "Prevent negative values in UI" -- and it did
      // not: the state was wiped but the field still showed «-5», leaving a
      // confusing dead end (no error text, since validationError bails on empty
      // at TopupView.vue:125, and a disabled «Пополнить» with no amount).
      //
      // The cause was in VInput, not here: when a parent rejects a value back to
      // the one it already held, `modelValue` does not change, Vue skips the
      // child update, and the typed text is never overwritten. VInput now
      // re-asserts the parent's value onto the DOM (VInput.vue onInput); the
      // component-level contract is pinned in VInput.test.ts.
      mount()
      await flush()
      toggleCustom()
      await flush()
      typeCustom('-5')
      await flush()

      const input = host?.querySelector<HTMLInputElement>('.topup__custom input')
      expect(input?.value).toBe('')
      expect(text()).not.toContain('Минимальная сумма')
    })
  })

  describe('C-1 checkout redirect whitelist (TopupView.vue:168-170)', () => {
    it('redirects to a Stripe checkout url', async () => {
      vi.mocked(paymentsApi.createTopup).mockResolvedValue(topup('https://checkout.stripe.com/c/pay/session_123'))
      mount()
      await flush()

      submitBtn()?.click()
      await flush()

      expect(location.href).toBe('https://checkout.stripe.com/c/pay/session_123')
      expect(toastError).not.toHaveBeenCalled()
    })

    it('redirects to the API base url (stub mode)', async () => {
      vi.mocked(paymentsApi.createTopup).mockResolvedValue(topup('https://api.talentir.info/api/v1/payments/stub-success'))
      mount()
      await flush()

      submitBtn()?.click()
      await flush()

      expect(location.href).toBe('https://api.talentir.info/api/v1/payments/stub-success')
    })

    it('REFUSES to navigate to a url outside the whitelist', async () => {
      // The open-redirect guard. If the backend is compromised (or the env
      // fallback ever collapses to an empty prefix), this is the only thing
      // between the user and an attacker-controlled payment page.
      vi.mocked(paymentsApi.createTopup).mockResolvedValue(topup('https://evil.example.com/pay'))
      mount()
      await flush()

      submitBtn()?.click()
      await flush()

      expect(location.href).toBe('')
      expect(toastError).toHaveBeenCalledWith('Некорректный URL платёжной системы')
    })

    it('REFUSES a look-alike host that merely CONTAINS the allowed prefix', async () => {
      // startsWith, not includes -- `https://evil.com/?next=https://checkout.stripe.com/`
      // must not pass. A contains-check here would be a working open redirect.
      vi.mocked(paymentsApi.createTopup).mockResolvedValue(topup('https://evil.example.com/?next=https://checkout.stripe.com/c/pay/x'))
      mount()
      await flush()

      submitBtn()?.click()
      await flush()

      expect(location.href).toBe('')
      expect(toastError).toHaveBeenCalledWith('Некорректный URL платёжной системы')
    })

    it('a blocked redirect leaves the button usable again', async () => {
      // The `finally` (TopupView.vue:193-195) must clear loading even on the
      // early `return` inside try -- otherwise a single bad url would wedge the
      // screen and the user could never retry.
      vi.mocked(paymentsApi.createTopup).mockResolvedValue(topup('https://evil.example.com/pay'))
      mount()
      await flush()

      submitBtn()?.click()
      await flush()

      expect(submitBtn()?.disabled).toBe(false)
    })
  })

  describe('submit failures', () => {
    it('surfaces the REAL backend detail on an ApiResponseError', async () => {
      // TopupView.vue:188-189 toasts e.detail verbatim -- so «Payments are
      // temporarily unavailable» from the backend must reach the user, not a
      // generic fallback that hides why the money did not move.
      vi.mocked(paymentsApi.createTopup).mockRejectedValue(
        new ApiResponseError(503, 'Платежи временно недоступны', 'stripe_down'),
      )
      mount()
      await flush()

      submitBtn()?.click()
      await flush()

      expect(toastError).toHaveBeenCalledWith('Платежи временно недоступны')
      expect(location.href).toBe('')
    })

    it('falls back to a generic message on a non-API error', async () => {
      vi.mocked(paymentsApi.createTopup).mockRejectedValue(new TypeError('boom'))
      mount()
      await flush()

      submitBtn()?.click()
      await flush()

      expect(toastError).toHaveBeenCalledWith('Не удалось создать платёж')
    })

    it('a failure leaves the button usable again', async () => {
      vi.mocked(paymentsApi.createTopup).mockRejectedValue(new TypeError('boom'))
      mount()
      await flush()

      submitBtn()?.click()
      await flush()

      expect(submitBtn()?.disabled).toBe(false)
    })

    it('does NOT double-charge when the button is clicked twice while in flight', async () => {
      // onTopup re-entry guard (TopupView.vue:173). A second POST here would
      // open a second Stripe session for the same intent.
      let resolve!: (v: TopupResponse) => void
      vi.mocked(paymentsApi.createTopup).mockReturnValue(
        new Promise<TopupResponse>((r) => {
          resolve = r
        }),
      )
      mount()
      await flush()

      submitBtn()?.click()
      await nextTick()
      submitBtn()?.click()
      await nextTick()

      expect(paymentsApi.createTopup).toHaveBeenCalledTimes(1)

      resolve(topup('https://checkout.stripe.com/c/pay/x'))
      await flush()
    })
  })
})
